services:
  requirements:
    container_name: config_generator
    build: ./server/src
    volumes:
      - ./.env:/app/.env:ro
      - ./server/src/config_templates:/app/templates
      - ./server/homeassistant/config/include:/app/output/include
      - ./server/appdaemon/config:/app/output/appdaemon
      - ./server/mosquitto/config:/app/output/mosquitto
    restart: "no"  # Optional: ensure it exits after generation

  homeassistant:
    container_name: homeassistant_kybfarm
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./server/homeassistant/config:/config 
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    ports:
      - "8123:8123"
    depends_on:
      - requirements
      - influxdb
    env_file:
      - .env

  appdaemon:
    container_name: appdaemon_kybfarm
    image: acockburn/appdaemon:latest
    volumes:
      - ./server/appdaemon/config:/conf
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      - "5050:5050"
    depends_on:
      - requirements
      - homeassistant
    env_file:
      - .env

  influxdb:
    container_name: influxdb_kybfarm
    image: influxdb:latest
    volumes:
      - ./server/influxdb/data:/var/lib/influxdb2
      - ./server/influxdb/config:/etc/influxdb2
    restart: unless-stopped
    ports:
      - "8086:8086"
    env_file:
      - .env

  mqtt:
    container_name: mqtt_kybfarm
    image: eclipse-mosquitto:latest
    volumes:
      - ./server/mosquitto/config:/mosquitto/config
      - ./server/mosquitto/data:/mosquitto/data
      - ./server/mosquitto/log:/mosquitto/log
    restart: unless-stopped
    ports:
      - "1883:1883"
    depends_on:
      - requirements
    env_file:
      - .env
