version: "3"
services:
  homeassistant:
    container_name: homeassistant_kybfarm
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./server/homeassistant/config:/config 
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    ports:
      - 8123:8123
    depends_on:
      - influxdb-service
    env_file:
      - .env

  appdaemon:
    container_name: appdaemon_kybfarm
    image: acockburn/appdaemon:latest
    volumes:
      - /etc/localtime:/etc/localtime
      - ./server/appdaemon/config:/conf
    # environment:
    #  - HA_URL=${APPDAEMON_HA_URL:?error}
    #  - TOKEN=${APPDAEMON_TOKEN:?error}
    ports:
      - 5050:5050
    depends_on:
      - homeassistant
    restart: always
    env_file:
      - .env


  influxdb-service:
    image: influxdb:latest
    container_name: influxdb_kybfarm
    restart: always
    ports:
      - 8086:8086
    volumes:
      - ./server/influxdb/data:/var/lib/influxdb2
      - ./server/influxdb/config:/etc/influxdb2
    env_file:
      - .env
    # environment:
    #   - DOCKER_INFLUXDB_INIT_MODE=setup
    #   - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME:?error}
    #   - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD:?error}
    #   - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG:?error}
    #   - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET:?error}
    #   - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN:?error}

  tunnel:
    container_name: cloudflared_tunnel_kybfarm
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    env_file:
      - .env
    # environment:
    #  - TUNNEL_TOKEN=${CLOUDFLARE_TOKEN:?error}

