version: "3"

services:
  homeassistant:
    container_name: homeassistant_kybfarm
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./server/homeassistant/config:/config 
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro  # For bluetooth integration
    restart: unless-stopped
    privileged: true
    # network_mode: host  # (Apparently, this does not work when using Docker Desktop. Must instead add ports manually.)
    ports:
      - 8123:8123
    depends_on:
      - influxdb
    env_file:
      - .env

  appdaemon:
    container_name: appdaemon_kybfarm
    image: acockburn/appdaemon:latest
    volumes:
      - ./server/appdaemon/config:/conf
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      - 5050:5050
    depends_on:
      - homeassistant
    env_file:
      - .env


  influxdb:
    container_name: influxdb_kybfarm
    image: influxdb:latest
    volumes:
      - ./server/influxdb/data:/var/lib/influxdb2
      - ./server/influxdb/config:/etc/influxdb2
    restart: unless-stopped
    ports:
      - 8086:8086
    env_file:
      - .env

  tunnel:
    container_name: cloudflared_tunnel_kybfarm
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    env_file:
      - .env
