version: "3"

services:
  vff_simulator:
    container_name: vff_simulator
    build: ./server/src/containers/vff_simulator
    restart: unless-stopped
    depends_on:
      - mqtt
    env_file:
      - .env

  temperature_sensor_simulator:
    container_name: temperature_sensor_simulator
    build: ./server/src/containers/temperature_sensor_simulator
    restart: unless-stopped
    depends_on:
      - mqtt
      - vff_simulator
    env_file:
      - .env

  heat_pump_simulator:
    container_name: heat_pump_simulator
    build: ./server/src/containers/heat_pump_simulator
    restart: unless-stopped
    depends_on:
      - mqtt
      - vff_simulator
    env_file:
      - .env

  mqtt:
    container_name: mqtt_broker
    image: eclipse-mosquitto:2
    volumes:
      - ./server/mosquitto/config:/mosquitto/config
      - ./server/mosquitto/data:/mosquitto/data
      - ./server/mosquitto/log:/mosquitto/log
    restart: unless-stopped
    ports:
      - "1883:1883"
    env_file:
      - .env

  homeassistant:
    container_name: home_assistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./server/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      # - /run/dbus:/run/dbus:ro  # (Optional) For bluetooth integration
    restart: unless-stopped
    privileged: true
    ports:
      - "8123:8123"
    depends_on:
      - mqtt
    env_file:
      - .env

  influxdb:
    container_name: influxdb
    image: influxdb:latest
    volumes:
      - influxdb:/var/lib/influxdb2
      - influxdb:/etc/influxdb2
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      - "8086:8086"
    env_file:
      - .env

  appdaemon:
    container_name: appdaemon
    image: acockburn/appdaemon:latest
    volumes:
      - ./server/appdaemon/config:/conf
      - /etc/localtime:/etc/localtime:ro
      - appdaemon:/certs  # Added because AppDaemon kept creating a new volume on each startup.
    restart: unless-stopped
    ports:
      - "5050:5050"
    depends_on:
      - homeassistant
      - influxdb
    env_file:
      - .env

volumes:
  influxdb:
  appdaemon: