# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Add additional containers directly to the Home Assistant dashboard
panel_iframe:
  appdaemon:
    title: "AppDaemon"
    icon: "mdi:application"
    url: {{APPDAEMON_URL}}
    require_admin: true
  influxdb:
    title: "InfluxDB"
    icon: "mdi:database"
    url: {{INFLUXDB_URL}}
    require_admin: true

automation: !include automations.yaml
# script: !include scripts.yaml
# scene: !include scenes.yaml

# InfluxDB Database configuration
influxdb: !include influxdb.yaml

# Helpers for GUI
input_number: !include input_number.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
input_text: !include input_text.yaml
input_datetime: !include input_datetime.yaml

# MQTT Configuration to receive MQTT data
mqtt:
  # Broker configuration: Must be done in GUI
  
  # Sensor configuration
  sensor:
    - name: {{LIGHT_01_NAME}}
      unique_id: {{LIGHT_01_HA_ID}}
      state_topic: {{MQTT_SENSOR_01_DT_RES}}
      value_template: {{LIGHT_01_VALUE_TEMPLATE}}
      unit_of_measurement: {{LIGHT_01_HA_UNIT}}
      icon: {{LIGHT_01_HA_ICON}}

    - name: {{PAR_02_NAME}}
      unique_id: {{PAR_02_HA_ID}}
      state_topic: {{MQTT_SENSOR_02_DT_RES}}
      value_template: {{PAR_02_VALUE_TEMPLATE}}
      unit_of_measurement: {{PAR_02_HA_UNIT}}
      icon: {{PAR_02_HA_ICON}}
    
    - name: {{EC_03_NAME}}
      unique_id: {{EC_03_HA_ID}}
      state_topic: {{MQTT_SENSOR_03_DT_RES}}
      value_template: {{EC_03_VALUE_TEMPLATE}}
      unit_of_measurement: {{EC_03_HA_UNIT}}
      icon: {{EC_03_HA_ICON}}

    - name: {{TEMPERATURE_03_NAME}}
      unique_id: {{TEMPERATURE_03_HA_ID}}
      state_topic: {{MQTT_SENSOR_03_DT_RES}}
      value_template: {{TEMPERATURE_03_VALUE_TEMPLATE}}
      unit_of_measurement: {{TEMPERATURE_03_HA_UNIT}}
      icon: {{TEMPERATURE_03_HA_ICON}}

    - name: {{TDS_03_NAME}}
      unique_id: {{TDS_03_HA_ID}}
      state_topic: {{MQTT_SENSOR_03_DT_RES}}
      value_template: {{TDS_03_VALUE_TEMPLATE}}
      unit_of_measurement: {{TDS_03_HA_UNIT}}
      icon: {{TDS_03_HA_ICON}}
          
    - name: {{SENSOR_03_CALIBRATION_NAME}}
      unique_id: {{SENSOR_03_CALIBRATION_HA_ID}}
      state_topic: {{MQTT_SENSOR_03_DT_RES}}
      value_template: {{EC_03_CALIBRATION_VALUE_TEMPLATE}}
      unit_of_measurement: {{EC_03_CALIBRATION_UNIT}}
      icon: {{EC_03_HA_ICON}}

    - name: {{EC_04_NAME}}
      unique_id: {{EC_04_HA_ID}}
      state_topic: {{MQTT_SENSOR_04_DT_RES}}
      value_template: {{EC_04_VALUE_TEMPLATE}}
      unit_of_measurement: {{EC_04_HA_UNIT}}
      icon: {{EC_04_HA_ICON}}

    - name: {{TEMPERATURE_04_NAME}}
      unique_id: {{TEMPERATURE_04_HA_ID}}
      state_topic: {{MQTT_SENSOR_04_DT_RES}}
      value_template: {{TEMPERATURE_04_VALUE_TEMPLATE}}
      unit_of_measurement: {{TEMPERATURE_04_HA_UNIT}}
      icon: {{TEMPERATURE_04_HA_ICON}}

    - name: {{TDS_04_NAME}}
      unique_id: {{TDS_04_HA_ID}}
      state_topic: {{MQTT_SENSOR_04_DT_RES}}
      value_template: {{TDS_04_VALUE_TEMPLATE}}
      unit_of_measurement: {{TDS_04_HA_UNIT}}
      icon: {{TDS_04_HA_ICON}}

    - name: {{SENSOR_04_CALIBRATION_NAME}}
      unique_id: {{SENSOR_04_CALIBRATION_HA_ID}}
      state_topic: {{MQTT_SENSOR_04_DT_RES}}
      value_template: {{EC_04_CALIBRATION_VALUE_TEMPLATE}}
      unit_of_measurement: {{EC_04_CALIBRATION_UNIT}}
      icon: {{EC_04_HA_ICON}}

    - name: {{PH_05_NAME}}
      unique_id: {{PH_05_HA_ID}}
      state_topic: {{MQTT_SENSOR_05_DT_RES}}
      value_template: {{PH_05_VALUE_TEMPLATE}}
      unit_of_measurement: {{PH_05_HA_UNIT}}
      icon: {{PH_05_HA_ICON}}

    - name: {{TEMPERATURE_05_NAME}}
      unique_id: {{TEMPERATURE_05_HA_ID}}
      state_topic: {{MQTT_SENSOR_05_DT_RES}}
      value_template: {{TEMPERATURE_05_VALUE_TEMPLATE}}
      unit_of_measurement: {{TEMPERATURE_05_HA_UNIT}}
      icon: {{TEMPERATURE_05_HA_ICON}}

    - name: {{SENSOR_05_CALIBRATION_NAME}}
      unique_id: {{SENSOR_05_CALIBRATION_HA_ID}}
      state_topic: {{MQTT_SENSOR_05_DT_RES}}
      value_template: {{PH_05_CALIBRATION_VALUE_TEMPLATE}}
      unit_of_measurement: {{PH_05_CALIBRATION_UNIT}}
      icon: {{PH_05_HA_ICON}}

    - name: {{PH_06_NAME}}
      unique_id: {{PH_06_HA_ID}}
      state_topic: {{MQTT_SENSOR_06_DT_RES}}
      value_template: {{PH_06_VALUE_TEMPLATE}}
      unit_of_measurement: {{PH_06_HA_UNIT}}
      icon: {{PH_06_HA_ICON}}

    - name: {{TEMPERATURE_06_NAME}}
      unique_id: {{TEMPERATURE_06_HA_ID}}
      state_topic: {{MQTT_SENSOR_06_DT_RES}}
      value_template: {{TEMPERATURE_06_VALUE_TEMPLATE}}
      unit_of_measurement: {{TEMPERATURE_06_HA_UNIT}}
      icon: {{TEMPERATURE_06_HA_ICON}}

    - name: {{SENSOR_06_CALIBRATION_NAME}}
      unique_id: {{SENSOR_06_CALIBRATION_HA_ID}}
      state_topic: {{MQTT_SENSOR_06_DT_RES}}
      value_template: {{PH_06_CALIBRATION_VALUE_TEMPLATE}}
      unit_of_measurement: {{PH_06_CALIBRATION_UNIT}}
      icon: {{PH_06_HA_ICON}}

    - name: {{TEMPERATURE_11_NAME}}
      unique_id: {{TEMPERATURE_11_HA_ID}}
      state_topic: {{MQTT_SENSOR_11_DT_RES}}
      value_template: {{TEMPERATURE_11_VALUE_TEMPLATE}}
      unit_of_measurement: {{TEMPERATURE_11_HA_UNIT}}
      icon: {{TEMPERATURE_11_HA_ICON}}

    - name: {{HUMIDITY_11_NAME}}
      unique_id: {{HUMIDITY_11_HA_ID}}
      state_topic: {{MQTT_SENSOR_11_DT_RES}}
      value_template: {{HUMIDITY_11_VALUE_TEMPLATE}}
      unit_of_measurement: {{HUMIDITY_11_HA_UNIT}}
      icon: {{HUMIDITY_11_HA_ICON}}

    - name: {{CO2_11_NAME}}
      unique_id: {{CO2_11_HA_ID}}
      state_topic: {{MQTT_SENSOR_11_DT_RES}}
      value_template: {{CO2_11_VALUE_TEMPLATE}}
      unit_of_measurement: {{CO2_11_HA_UNIT}}
      icon: {{CO2_11_HA_ICON}}

    - name: {{DEWPOINT_11_NAME}}
      unique_id: {{DEWPOINT_11_HA_ID}}
      state_topic: {{MQTT_SENSOR_11_DT_RES}}
      value_template: {{DEWPOINT_11_VALUE_TEMPLATE}}
      unit_of_measurement: {{DEWPOINT_11_HA_UNIT}}
      icon: {{DEWPOINT_11_HA_ICON}}

    - name: {{VOLUMEFLOW_11_NAME}}
      unique_id: {{VOLUMEFLOW_11_HA_ID}}
      state_topic: {{MQTT_SENSOR_11_DT_RES}}
      value_template: {{VOLUMEFLOW_11_VALUE_TEMPLATE}}
      unit_of_measurement: {{VOLUMEFLOW_11_HA_UNIT}}
      icon: {{VOLUMEFLOW_11_HA_ICON}}

      # --------- LEGGER TIL NY SENSOR ---------------

    - name: {{TEMPERATURE_12_NAME}}
      unique_id: {{TEMPERATURE_12_HA_ID}}
      state_topic: {{MQTT_SENSOR_12_DT_RES}}
      value_template: {{TEMPERATURE_12_VALUE_TEMPLATE}}
      unit_of_measurement: {{TEMPERATURE_12_HA_UNIT}}
      icon: {{TEMPERATURE_12_HA_ICON}}

    - name: {{HUMIDITY_12_NAME}}
      unique_id: {{HUMIDITY_12_HA_ID}}
      state_topic: {{MQTT_SENSOR_12_DT_RES}}
      value_template: {{HUMIDITY_12_VALUE_TEMPLATE}}
      unit_of_measurement: {{HUMIDITY_12_HA_UNIT}}
      icon: {{HUMIDITY_12_HA_ICON}}

    - name: {{CO2_12_NAME}}
      unique_id: {{CO2_12_HA_ID}}
      state_topic: {{MQTT_SENSOR_12_DT_RES}}
      value_template: {{CO2_12_VALUE_TEMPLATE}}
      unit_of_measurement: {{CO2_12_HA_UNIT}}
      icon: {{CO2_12_HA_ICON}}

    - name: {{DEWPOINT_12_NAME}}
      unique_id: {{DEWPOINT_12_HA_ID}}
      state_topic: {{MQTT_SENSOR_12_DT_RES}}
      value_template: {{DEWPOINT_12_VALUE_TEMPLATE}}
      unit_of_measurement: {{DEWPOINT_12_HA_UNIT}}
      icon: {{DEWPOINT_12_HA_ICON}}

    - name: {{VOLUMEFLOW_12_NAME}}
      unique_id: {{VOLUMEFLOW_12_HA_ID}}
      state_topic: {{MQTT_SENSOR_12_DT_RES}}
      value_template: {{VOLUMEFLOW_12_VALUE_TEMPLATE}}
      unit_of_measurement: {{VOLUMEFLOW_12_HA_UNIT}}
      icon: {{VOLUMEFLOW_12_HA_ICON}}

 # --------- LEGGER TIL NY TEMP SENSOR ---------------
      
    - name: {{TEMPERATURE_13_NAME}}
      unique_id: {{TEMPERATURE_13_HA_ID}}
      state_topic: {{MQTT_SENSOR_13_DT_RES}}
      value_template: {{TEMPERATURE_13_VALUE_TEMPLATE}}
      unit_of_measurement: {{TEMPERATURE_13_HA_UNIT}}
      icon: {{TEMPERATURE_13_HA_ICON}}

    - name: {{HUMIDITY_13_NAME}}
      unique_id: {{HUMIDITY_13_HA_ID}}
      state_topic: {{MQTT_SENSOR_13_DT_RES}}
      value_template: {{HUMIDITY_13_VALUE_TEMPLATE}}
      unit_of_measurement: {{HUMIDITY_13_HA_UNIT}}
      icon: {{HUMIDITY_13_HA_ICON}}

    - name: {{DEWPOINT_13_NAME}}
      unique_id: {{DEWPOINT_13_HA_ID}}
      state_topic: {{MQTT_SENSOR_13_DT_RES}}
      value_template: {{DEWPOINT_13_VALUE_TEMPLATE}}
      unit_of_measurement: {{DEWPOINT_13_HA_UNIT}}
      icon: {{DEWPOINT_13_HA_ICON}}
    
    - name: {{TEMPERATURE_14_NAME}}
      unique_id: {{TEMPERATURE_14_HA_ID}}
      state_topic: {{MQTT_SENSOR_14_DT_RES}}
      value_template: {{TEMPERATURE_14_VALUE_TEMPLATE}}
      unit_of_measurement: {{TEMPERATURE_14_HA_UNIT}}
      icon: {{TEMPERATURE_14_HA_ICON}}

    - name: {{HUMIDITY_14_NAME}}
      unique_id: {{HUMIDITY_14_HA_ID}}
      state_topic: {{MQTT_SENSOR_14_DT_RES}}
      value_template: {{HUMIDITY_14_VALUE_TEMPLATE}}
      unit_of_measurement: {{HUMIDITY_14_HA_UNIT}}
      icon: {{HUMIDITY_14_HA_ICON}}

    - name: {{DEWPOINT_14_NAME}}
      unique_id: {{DEWPOINT_14_HA_ID}}
      state_topic: {{MQTT_SENSOR_14_DT_RES}}
      value_template: {{DEWPOINT_14_VALUE_TEMPLATE}}
      unit_of_measurement: {{DEWPOINT_14_HA_UNIT}}
      icon: {{DEWPOINT_14_HA_ICON}}

    - name: {{P_10_NAME}}
      unique_id: {{P_10_HA_ID}}
      state_topic: {{MQTT_P_10_STATE}}
      value_template: {{P_10_VALUE_TEMPLATE}}
      unit_of_measurement: {{P_10_HA_UNIT}}
      icon: {{P_10_HA_ICON}}

    - name: {{TEMPERATURE_10_NAME}}
      unique_id: {{TEMPERATURE_10_HA_ID}}
      state_topic: {{MQTT_SENSOR_10_DT_RES}}
      value_template: {{TEMPERATURE_10_VALUE_TEMPLATE}}
      unit_of_measurement: {{TEMPERATURE_10_HA_UNIT}}
      icon: {{TEMPERATURE_10_HA_ICON}}

    - name: {{LEAF_WETNESS_10_NAME}}
      unique_id: {{LEAF_WETNESS_10_HA_ID}}
      state_topic: {{MQTT_SENSOR_10_DT_RES}}
      value_template: {{LEAF_WETNESS_10_VALUE_TEMPLATE}}
      unit_of_measurement: {{LEAF_WETNESS_10_HA_UNIT}}
      icon: {{LEAF_WETNESS_10_HA_ICON}}




