  api_version: 2
  ssl: false
  host: 172.26.64.197 # Replace with the IP address of the host machine running InfluxDB
  port: 8086
  token: "2vcqRdwh74Ucsm9Dn49ZL9Pp6SO-GeQPzYmanCl-qHRm8ift9_dzeifZVwB9MQAtE9Ffne2WJ-3gB_pHxBIE3Q==" # Replace with the all-access API token generated in InfluxDB 
  organization: kybfarm
  bucket: FarmData
  tags:
    source: HA
  tags_attributes:
    - friendly_name
  default_measurement: units
  exclude:
    entities:
      - zone.home
    domains:
      - persistent_notification
      - person
  include:
    domains:
      - sensor
      - binary_sensor
 #     - 