# ┌────────────────────────────────────────────────────────────────────────────┐
# │                         Home Assistant Sensor Config                       │
# │                          KYBFarm - MQTT Sensor List                        │
# └────────────────────────────────────────────────────────────────────────────┘


# ────────────────────────────── TEMPLATE FORMAT ───────────────────────────── #
# - name:                "DISPLAY NAME [TYPE]"
#   unique_id:           "UNIQUE_SENSOR_ID"
#   state_topic:         "mqtt/topic"
#   value_template:      "{{ value_json['fields'].some_field }}"
#   unit_of_measurement: "unit"
#   icon:                "mdi:icon-name"
# ───────────────────────────────────────────────────────────────────────────── #


# ─────────────────────────────── S-PAR-02 ─────────────────────────────── #

## ───── PAR Sensor GT1 ─────
- name: "PAR Sensor 02 GT1 [PAR]"
  unique_id: "S-PAR-02_GT1_PAR"
  state_topic: "dt/gf/spar02/gt1/res"
  value_template: "{{ value_json['fields'].par }}"
  unit_of_measurement: "µmol/m²/s"
  icon: "mdi:white-balance-sunny"

## ───── PAR Sensor GT2 ─────
- name: "PAR Sensor 02 GT2 [PAR]"
  unique_id: "S-PAR-02_GT2_PAR"
  state_topic: "dt/gf/spar02/gt2/res"
  value_template: "{{ value_json['fields'].par }}"
  unit_of_measurement: "µmol/m²/s"
  icon: "mdi:white-balance-sunny"


# ─────────────────────────────── S-EC-01 ─────────────────────────────── #

## ───── EC Sensor GT1 ─────
- name: "EC Sensor GT1 [EC]"
  unique_id: "S-EC-01_GT1_EC"
  state_topic: "dt/gf/sec01/gt1/res"
  value_template: "{{ value_json['fields'].ec }}"
  unit_of_measurement: "µS/cm"
  icon: "mdi:flash"

- name: "EC Sensor GT1 [Temperature]"
  unique_id: "S-EC-01_GT1_TEMP"
  state_topic: "dt/gf/sec01/gt1/res"
  value_template: "{{ value_json['fields'].temperature }}"
  unit_of_measurement: "°C"
  icon: "mdi:thermometer"

- name: "EC Sensor GT1 [TDS]"
  unique_id: "S-EC-01_GT1_TDS"
  state_topic: "dt/gf/sec01/gt1/res"
  value_template: "{{ value_json['fields'].tds }}"
  unit_of_measurement: "mg/L"
  icon: "mdi:water"

- name: "EC Sensor GT1 [Calibration]"
  unique_id: "S-EC-01_GT1_CALIBRATION"
  state_topic: "dt/gf/sec01/gt1/res"
  value_template: "{{ (value_json['fields'].calibrated if value_json['fields'].calibrated != 0 else '1970-01-01T00:00:00Z') | as_timestamp | round(0) }}"
  unit_of_measurement: "timestamp"
  icon: "mdi:calendar-clock"

## ───── EC Sensor GT2 ─────
- name: "EC Sensor GT2 [EC]"
  unique_id: "S-EC-01_GT2_EC"
  state_topic: "dt/gf/sec01/gt2/res"
  value_template: "{{ value_json['fields'].ec }}"
  unit_of_measurement: "µS/cm"
  icon: "mdi:flash"

- name: "EC Sensor GT2 [Temperature]"
  unique_id: "S-EC-01_GT2_TEMP"
  state_topic: "dt/gf/sec01/gt2/res"
  value_template: "{{ value_json['fields'].temperature }}"
  unit_of_measurement: "°C"
  icon: "mdi:thermometer"

- name: "EC Sensor GT2 [TDS]"
  unique_id: "S-EC-01_GT2_TDS"
  state_topic: "dt/gf/sec01/gt2/res"
  value_template: "{{ value_json['fields'].tds }}"
  unit_of_measurement: "mg/L"
  icon: "mdi:water"

- name: "EC Sensor GT2 [Calibration]"
  unique_id: "S-EC-01_GT2_CALIBRATION"
  state_topic: "dt/gf/sec01/gt2/res"
  value_template: "{{ (value_json['fields'].calibrated if value_json['fields'].calibrated != 0 else '1970-01-01T00:00:00Z') | as_timestamp | round(0) }}"
  unit_of_measurement: "timestamp"
  icon: "mdi:calendar-clock"

## ───── EC Sensor MX ─────
- name: "EC Sensor MX [EC]"
  unique_id: "S-EC-01_MX_EC"
  state_topic: "dt/gf/sec01/mx/res"
  value_template: "{{ value_json['fields'].ec }}"
  unit_of_measurement: "µS/cm"
  icon: "mdi:flash"

- name: "EC Sensor MX [Temperature]"
  unique_id: "S-EC-01_MX_TEMP"
  state_topic: "dt/gf/sec01/mx/res"
  value_template: "{{ value_json['fields'].temperature }}"
  unit_of_measurement: "°C"
  icon: "mdi:thermometer"

- name: "EC Sensor MX [TDS]"
  unique_id: "S-EC-01_MX_TDS"
  state_topic: "dt/gf/sec01/mx/res"
  value_template: "{{ value_json['fields'].tds }}"
  unit_of_measurement: "mg/L"
  icon: "mdi:water"

- name: "EC Sensor MX [Calibration]"
  unique_id: "S-EC-01_MX_CALIBRATION"
  state_topic: "dt/gf/sec01/mx/res"
  value_template: "{{ (value_json['fields'].calibrated if value_json['fields'].calibrated != 0 else '1970-01-01T00:00:00Z') | as_timestamp | round(0) }}"
  unit_of_measurement: "timestamp"
  icon: "mdi:calendar-clock"


# ─────────────────────────────── S-PH-01 ─────────────────────────────── #

## ───── pH Sensor GT1 ─────
- name: "pH Sensor GT1 [pH]"
  unique_id: "S-PH-01_GT1_PH"
  state_topic: "dt/gf/sph01/gt1/res"
  value_template: "{{ value_json['fields'].ph }}"
  unit_of_measurement: "pH"
  icon: "mdi:ph"

- name: "pH Sensor GT1 [Temperature]"
  unique_id: "S-PH-01_GT1_TEMP"
  state_topic: "dt/gf/sph01/gt1/res"
  value_template: "{{ value_json['fields'].temperature }}"
  unit_of_measurement: "°C"
  icon: "mdi:thermometer"

- name: "pH Sensor GT1 [Calibration]"
  unique_id: "S-PH-01_GT1_CALIBRATION"
  state_topic: "dt/gf/sph01/gt1/res"
  value_template: "{{ (value_json['fields'].calibrated if value_json['fields'].calibrated != 0 else '1970-01-01T00:00:00Z') | as_timestamp | round(0) }}"
  unit_of_measurement: "timestamp"
  icon: "mdi:calendar-clock"

## ───── pH Sensor GT2 ─────
- name: "pH Sensor GT2 [pH]"
  unique_id: "S-PH-01_GT2_PH"
  state_topic: "dt/gf/sph01/gt2/res"
  value_template: "{{ value_json['fields'].ph }}"
  unit_of_measurement: "pH"
  icon: "mdi:ph"

- name: "pH Sensor GT2 [Temperature]"
  unique_id: "S-PH-01_GT2_TEMP"
  state_topic: "dt/gf/sph01/gt2/res"
  value_template: "{{ value_json['fields'].temperature }}"
  unit_of_measurement: "°C"
  icon: "mdi:thermometer"

- name: "pH Sensor GT2 [Calibration]"
  unique_id: "S-PH-01_GT2_CALIBRATION"
  state_topic: "dt/gf/sph01/gt2/res"
  value_template: "{{ (value_json['fields'].calibrated if value_json['fields'].calibrated != 0 else '1970-01-01T00:00:00Z') | as_timestamp | round(0) }}"
  unit_of_measurement: "timestamp"
  icon: "mdi:calendar-clock"

## ───── pH Sensor MX ─────
- name: "pH Sensor MX [pH]"
  unique_id: "S-PH-01_MX_PH"
  state_topic: "dt/gf/sph01/mx/res"
  value_template: "{{ value_json['fields'].ph }}"
  unit_of_measurement: "pH"
  icon: "mdi:ph"

- name: "pH Sensor MX [Temperature]"
  unique_id: "S-PH-01_MX_TEMP"
  state_topic: "dt/gf/sph01/mx/res"
  value_template: "{{ value_json['fields'].temperature }}"
  unit_of_measurement: "°C"
  icon: "mdi:thermometer"

- name: "pH Sensor MX [Calibration]"
  unique_id: "S-PH-01_MX_CALIBRATION"
  state_topic: "dt/gf/sph01/mx/res"
  value_template: "{{ (value_json['fields'].calibrated if value_json['fields'].calibrated != 0 else '1970-01-01T00:00:00Z') | as_timestamp | round(0) }}"
  unit_of_measurement: "timestamp"
  icon: "mdi:calendar-clock"


# ─────────────────────────────── CO2/VOC Sensor ─────────────────────────────── #

## ───── CO2/VOC Sensor ─────
- name: "CO2/VOC Sensor [Temperature]"
  unique_id: "CO2_VOC_1_TEMP"
  state_topic: "dt/gf/co2voc/1/res"
  value_template: "{{ value_json['fields'].temperature }}"
  unit_of_measurement: "°C"
  icon: "mdi:thermometer"

- name: "CO2/VOC Sensor [Humidity]"
  unique_id: "CO2_VOC_1_RH"
  state_topic: "dt/gf/co2voc/1/res"
  value_template: "{{ value_json['fields'].humidity }}"
  unit_of_measurement: "%[RH]"
  icon: "mdi:water-percent"

- name: "CO2/VOC Sensor 1 [CO2]"
  unique_id: "CO2_VOC_1_CO2"
  state_topic: "dt/gf/co2voc/1/res"
  value_template: "{{ value_json['fields'].co2 }}"
  unit_of_measurement: "ppm"
  icon: "mdi:molecule-co2"

- name: "CO2/VOC Sensor 1 [Dewpoint]"
  unique_id: "CO2_VOC_1_DP"
  state_topic: "dt/gf/co2voc/1/res"
  value_template: "{{ value_json['fields'].dewpoint }}"
  unit_of_measurement: "°C"
  icon: "mdi:thermometer-water"

- name: "CO2/VOC Sensor 1 [Volume Flow]"
  unique_id: "CO2_VOC_1_VF"
  state_topic: "dt/gf/co2voc/1/res"
  value_template: "{{ value_json['fields'].volumeFlow }}"
  unit_of_measurement: "m3/s"
  icon: "mdi:air-filter"


# ─────────────────────────────── S-TH-01 ─────────────────────────────── #

## ───── STH Sensor 1 ─────
- name: "STH Sensor 1 [Temperature]"
  unique_id: "STH01_1_TEMP"
  state_topic: "dt/gf/sth01/1/res"
  value_template: "{{ value_json['fields'].temperature }}"
  unit_of_measurement: "°C"
  icon: "mdi:thermometer"

- name: "STH Sensor 1 [Humidity]"
  unique_id: "STH01_1_RH"
  state_topic: "dt/gf/sth01/1/res"
  value_template: "{{ value_json['fields'].humidity }}"
  unit_of_measurement: "%[RH]"
  icon: "mdi:water-percent"

- name: "STH Sensor 1 [Dewpoint]"
  unique_id: "STH01_1_DP"
  state_topic: "dt/gf/sth01/1/res"
  value_template: "{{ value_json['fields'].dewpoint }}"
  unit_of_measurement: "°C"
  icon: "mdi:thermometer-water"

## ───── STH Sensor 2 ─────
- name: "STH Sensor 2 [Temperature]"
  unique_id: "STH01_2_TEMP"
  state_topic: "dt/gf/sth01/2/res"
  value_template: "{{ value_json['fields'].temperature }}"
  unit_of_measurement: "°C"
  icon: "mdi:thermometer"

- name: "STH Sensor 2 [Humidity]"
  unique_id: "STH01_2_RH"
  state_topic: "dt/gf/sth01/2/res"
  value_template: "{{ value_json['fields'].humidity }}"
  unit_of_measurement: "%[RH]"
  icon: "mdi:water-percent"

- name: "STH Sensor 2 [Dewpoint]"
  unique_id: "STH01_2_DP"
  state_topic: "dt/gf/sth01/2/res"
  value_template: "{{ value_json['fields'].dewpoint }}"
  unit_of_measurement: "°C"
  icon: "mdi:thermometer-water"



# ─────────────────────────────── S-YM-01 ─────────────────────────────── #

## ───── SYM01 Leaf Wetness Sensor ─────
- name: "SYM01 [Temperature]"
  unique_id: "S-YM-01_TEMP"
  state_topic: "dt/gf/sym01/res"
  value_template: "{{ value_json['fields'].temperature }}"
  unit_of_measurement: "°C"
  icon: "mdi:thermometer"

- name: "SYM01 [Leaf Wetness]"
  unique_id: "S-YM-01_LEAF_WETNESS"
  state_topic: "dt/gf/sym01/res"
  value_template: "{{ value_json['fields'].wetness }}"
  unit_of_measurement: "%[Leaf Wetness]"
  icon: "mdi:leaf"


# ─────────────────────────────── Dummy Control Signal ─────────────────────────────── #

- name: "Dummy Temperature Control Signal [Float]"
  unique_id: "GF_P_10"
  state_topic: "ha/desktop_gf/actuators/temperature"
  value_template: "{{ (value_json['control_signal'] | float) | round(2) }}"
  unit_of_measurement: "[float]"
  icon: "mdi:heat-wave"
