# ┌────────────────────────────────────────────────────────────────────────────┐
# │                          Home Assistant MQTT Sensors                       │
# │                       KYBFarm – Sensor Data and Calibration                │
# └────────────────────────────────────────────────────────────────────────────┘

# ──────────────── CO2/VOC Sensor ────────────────

#─────── 1 ───────

- name: "CO2/VOC Sensor 1 [Humidity]"
  unique_id: "CO2_VOC_HUMIDITY"
  state_topic: "dt/gf/co2voc/1/res"
  value_template: "{{ value_json['fields'].humidity }}"
  unit_of_measurement: "%"
  icon: "mdi:water-percent"

- name: "CO2/VOC Sensor 1 [Temperature]"
  unique_id: "CO2_VOC_TEMPERATURE"
  state_topic: "dt/gf/co2voc/1/res"
  value_template: "{{ value_json['fields'].temperature }}"
  unit_of_measurement: "°C"
  icon: "mdi:thermometer"

- name: "CO2/VOC Sensor 1 [CO2]"
  unique_id: "CO2_VOC_1_CO2"
  state_topic: "dt/gf/co2voc/1/res"
  value_template: "{{ value_json['fields'].co2 }}"
  unit_of_measurement: "ppm"
  icon: "mdi:molecule-co2"

- name: "CO2/VOC Sensor 1 [Dewpoint]"
  unique_id: "CO2_VOC_1_DEWPOINT"
  state_topic: "dt/gf/co2voc/1/res"
  value_template: "{{ value_json['fields'].dewpoint }}"
  unit_of_measurement: "°C"
  icon: "mdi:thermometer-lines"

- name: "CO2/VOC Sensor 1 [Volume Flow]"
  unique_id: "CO2_VOC_1_VOLUME_FLOW"
  state_topic: "dt/gf/co2voc/1/res"
  value_template: "{{ value_json['fields'].volumeFlow }}"
  unit_of_measurement: "m³/h"
  icon: "mdi:air-filter"

# ─────── 2 ───────

- name: "CO2/VOC Sensor 2 [Humidity]"
  unique_id: "CO2_VOC_2_HUMIDITY"
  state_topic: "dt/gf/co2voc/2/res"
  value_template: "{{ value_json['fields'].humidity }}"
  unit_of_measurement: "%"
  icon: "mdi:water-percent"

- name: "CO2/VOC Sensor 2 [Temperature]"
  unique_id: "CO2_VOC_2_TEMPERATURE"
  state_topic: "dt/gf/co2voc/2/res"
  value_template: "{{ value_json['fields'].temperature }}"
  unit_of_measurement: "°C"
  icon: "mdi:thermometer"

- name: "CO2/VOC Sensor 2 [CO2]"
  unique_id: "CO2_VOC_2_CO2"
  state_topic: "dt/gf/co2voc/2/res"
  value_template: "{{ value_json['fields'].co2 }}"
  unit_of_measurement: "ppm"
  icon: "mdi:molecule-co2"

- name: "CO2/VOC Sensor 2 [Dewpoint]"
  unique_id: "CO2_VOC_2_DEWPOINT"
  state_topic: "dt/gf/co2voc/2/res"
  value_template: "{{ value_json['fields'].dewpoint }}"
  unit_of_measurement: "°C"
  icon: "mdi:thermometer-lines"

- name: "CO2/VOC Sensor 2 [Volume Flow]"
  unique_id: "CO2_VOC_2_VOLUME_FLOW"
  state_topic: "dt/gf/co2voc/2/res"
  value_template: "{{ value_json['fields'].volumeFlow }}"
  unit_of_measurement: "m³/h"
  icon: "mdi:air-filter"



# ──────────────── EC Sensor Calibrations ────────────────

- name: "EC Sensor GT1 [Calibration]"
  unique_id: "S-EC-01_GT1_CAL"
  state_topic: "cmd/ec_gt1/req"
  value_template: "{{ value_json['result'] if value_json.get('result') else value_json }}"
  icon: "mdi:checkbox-marked-circle-outline"

- name: "EC Sensor GT2 [Calibration]"
  unique_id: "S-EC-01_GT2_CAL"
  state_topic: "cmd/ec_gt2/req"
  value_template: "{{ value_json['result'] if value_json.get('result') else value_json }}"
  icon: "mdi:checkbox-marked-circle-outline"

- name: "EC Sensor MX [Calibration]"
  unique_id: "S-EC-01_MX_CAL"
  state_topic: "cmd/ec_mx/req"
  value_template: "{{ value_json['result'] if value_json.get('result') else value_json }}"
  icon: "mdi:checkbox-marked-circle-outline"

# ──────────────── pH Sensor Calibrations ────────────────

- name: "pH Sensor GT1 [Calibration]"
  unique_id: "S-PH-01_GT1_CAL"
  state_topic: "cmd/ph_gt1/req"
  value_template: "{{ value_json['result'] if value_json.get('result') else value_json }}"
  icon: "mdi:checkbox-marked-circle-outline"

- name: "pH Sensor GT2 [Calibration]"
  unique_id: "S-PH-01_GT2_CAL"
  state_topic: "cmd/ph_gt2/req"
  value_template: "{{ value_json['result'] if value_json.get('result') else value_json }}"
  icon: "mdi:checkbox-marked-circle-outline"

- name: "pH Sensor MX [Calibration]"
  unique_id: "S-PH-01_MX_CAL"
  state_topic: "cmd/ph_mx/req"
  value_template: "{{ value_json['result'] if value_json.get('result') else value_json }}"
  icon: "mdi:checkbox-marked-circle-outline"

# ──────────────── EC Sensors ────────────────

- name: "EC Sensor GT1 [EC]"
  unique_id: "S-EC-01_GT1_EC"
  state_topic: "dt/gf/sec01/gt1/res"
  value_template: "{{ value_json['fields'].ec }}"
  unit_of_measurement: "µS/cm"
  icon: "mdi:flash"

- name: "EC Sensor GT1 [TDS]"
  unique_id: "S-EC-01_GT1_TDS"
  state_topic: "dt/gf/sec01/gt1/res"
  value_template: "{{ value_json['fields'].tds }}"
  unit_of_measurement: "ppm"
  icon: "mdi:scale"

- name: "EC Sensor GT1 [Temperature]"
  unique_id: "S-EC-01_GT1_TEMP"
  state_topic: "dt/gf/sec01/gt1/res"
  value_template: "{{ value_json['fields'].temperature }}"
  unit_of_measurement: "°C"
  icon: "mdi:thermometer"

- name: "EC Sensor GT2 [EC]"
  unique_id: "S-EC-01_GT2_EC"
  state_topic: "dt/gf/sec01/gt2/res"
  value_template: "{{ value_json['fields'].ec }}"
  unit_of_measurement: "µS/cm"
  icon: "mdi:flash"

- name: "EC Sensor GT2 [TDS]"
  unique_id: "S-EC-01_GT2_TDS"
  state_topic: "dt/gf/sec01/gt2/res"
  value_template: "{{ value_json['fields'].tds }}"
  unit_of_measurement: "ppm"
  icon: "mdi:scale"

- name: "EC Sensor GT2 [Temperature]"
  unique_id: "S-EC-01_GT2_TEMP"
  state_topic: "dt/gf/sec01/gt2/res"
  value_template: "{{ value_json['fields'].temperature }}"
  unit_of_measurement: "°C"
  icon: "mdi:thermometer"

- name: "EC Sensor MX [EC]"
  unique_id: "S-EC-01_MX_EC"
  state_topic: "dt/gf/sec01/mx/res"
  value_template: "{{ value_json['fields'].ec }}"
  unit_of_measurement: "µS/cm"
  icon: "mdi:flash"

- name: "EC Sensor MX [TDS]"
  unique_id: "S-EC-01_MX_TDS"
  state_topic: "dt/gf/sec01/mx/res"
  value_template: "{{ value_json['fields'].tds }}"
  unit_of_measurement: "ppm"
  icon: "mdi:scale"

- name: "EC Sensor MX [Temperature]"
  unique_id: "S-EC-01_MX_TEMP"
  state_topic: "dt/gf/sec01/mx/res"
  value_template: "{{ value_json['fields'].temperature }}"
  unit_of_measurement: "°C"
  icon: "mdi:thermometer"

# ──────────────── PAR Sensors ────────────────

- name: "SLIGHT01 [Light Intensity]"
  unique_id: "S-LIGHT-01"
  state_topic: "dt/gf/slight01/res"
  value_template: "{{ value_json['fields'].illuminance }}"
  unit_of_measurement: "lx"
  icon: "mdi:white-balance-sunny"


- name: "PAR Sensor 02 GT2 [PAR]"
  unique_id: "S-PAR-02_GT2"
  state_topic: "dt/gf/spar02/gt2/res"
  value_template: "{{ value_json['fields'].par }}"
  unit_of_measurement: "µmol/m²/s"
  icon: "mdi:white-balance-sunny"

# ──────────────── pH Sensors ────────────────

- name: "pH Sensor GT1 [pH]"
  unique_id: "S-PH-01_GT1_PH"
  state_topic: "dt/gf/sph01/gt1/res"
  value_template: "{{ value_json['fields'].ph }}"
  unit_of_measurement: "pH"
  icon: "mdi:ph"

- name: "pH Sensor GT1 [Temperature]"
  unique_id: "S-PH-01_GT1_TEMP"
  state_topic: "dt/gf/sph01/gt1/res"
  value_template: "{{ value_json['fields'].temperature }}"
  unit_of_measurement: "°C"
  icon: "mdi:thermometer"

- name: "pH Sensor GT2 [pH]"
  unique_id: "S-PH-01_GT2_PH"
  state_topic: "dt/gf/sph01/gt2/res"
  value_template: "{{ value_json['fields'].ph }}"
  unit_of_measurement: "pH"
  icon: "mdi:ph"

- name: "pH Sensor GT2 [Temperature]"
  unique_id: "S-PH-01_GT2_TEMP"
  state_topic: "dt/gf/sph01/gt2/res"
  value_template: "{{ value_json['fields'].temperature }}"
  unit_of_measurement: "°C"
  icon: "mdi:thermometer"

- name: "pH Sensor MX [pH]"
  unique_id: "S-PH-01_MX_PH"
  state_topic: "dt/gf/sph01/mx/res"
  value_template: "{{ value_json['fields'].ph }}"
  unit_of_measurement: "pH"
  icon: "mdi:ph"

- name: "pH Sensor MX [Temperature]"
  unique_id: "S-PH-01_MX_TEMP"
  state_topic: "dt/gf/sph01/mx/res"
  value_template: "{{ value_json['fields'].temperature }}"
  unit_of_measurement: "°C"
  icon: "mdi:thermometer"

# ──────────────── STH Sensors ────────────────

- name: "STH Sensor 1 [Dewpoint]"
  unique_id: "STH01_1_DEWPOINT"
  state_topic: "dt/gf/sth01/1/res"
  value_template: "{{ value_json['fields'].dewpoint }}"
  unit_of_measurement: "°C"
  icon: "mdi:thermometer-lines"

- name: "STH Sensor 1 [Humidity]"
  unique_id: "STH01_1_HUMIDITY"
  state_topic: "dt/gf/sth01/1/res"
  value_template: "{{ value_json['fields'].humidity }}"
  unit_of_measurement: "%"
  icon: "mdi:water-percent"

- name: "STH Sensor 1 [Temperature]"
  unique_id: "STH01_1_TEMP"
  state_topic: "dt/gf/sth01/1/res"
  value_template: "{{ value_json['fields'].temperature }}"
  unit_of_measurement: "°C"
  icon: "mdi:thermometer"

- name: "STH Sensor 2 [Dewpoint]"
  unique_id: "STH01_2_DEWPOINT"
  state_topic: "dt/gf/sth01/2/res"
  value_template: "{{ value_json['fields'].dewpoint }}"
  unit_of_measurement: "°C"
  icon: "mdi:thermometer-lines"

- name: "STH Sensor 2 [Humidity]"
  unique_id: "STH01_2_HUMIDITY"
  state_topic: "dt/gf/sth01/2/res"
  value_template: "{{ value_json['fields'].humidity }}"
  unit_of_measurement: "%"
  icon: "mdi:water-percent"

- name: "STH Sensor 2 [Temperature]"
  unique_id: "STH01_2_TEMP"
  state_topic: "dt/gf/sth01/2/res"
  value_template: "{{ value_json['fields'].temperature }}"
  unit_of_measurement: "°C"
  icon: "mdi:thermometer"

# ──────────────── SYM01 ────────────────

- name: "SYM01 [Leaf Wetness]"
  unique_id: "S-YM-01_LEAF_WETNESS"
  state_topic: "dt/gf/sym01/res"
  value_template: "{{ value_json['fields'].wetness }}"
  unit_of_measurement: ""
  icon: "mdi:leaf"

- name: "SYM01 [Temperature]"
  unique_id: "S-YM-01_LEAF_TEMPERATURE"
  state_topic: "dt/gf/sym01/res"
  value_template: "{{ value_json['fields'].temperature }}"
  unit_of_measurement: ""
  icon: "mdi:thermometer"

# ──────────────── WLS01 ────────────────

# ───── Grow Tank 1 ─────
- name: "Water Level Sensor GT1 [Level]"
  unique_id: "WLS01_GT1_LEVEL"
  state_topic: "dt/gf/wls01/gt1/res"
  value_template: "{{ value_json['fields'].level_cm }}"
  unit_of_measurement: "cm"
  icon: "mdi:waves"

- name: "Water Level Sensor GT1 [Pressure]"
  unique_id: "WLS01_GT1_PRESSURE"
  state_topic: "dt/gf/wls01/gt1/res"
  value_template: "{{ value_json['fields'].pressure_kPa }}"
  unit_of_measurement: "kPa"
  icon: "mdi:gauge"

# ───── Grow Tank 2 ─────
- name: "Water Level Sensor GT2 [Level]"
  unique_id: "WLS01_GT2_LEVEL"
  state_topic: "dt/gf/wls01/gt2/res"
  value_template: "{{ value_json['fields'].level_cm }}"
  unit_of_measurement: "cm"
  icon: "mdi:waves"

- name: "Water Level Sensor GT2 [Pressure]"
  unique_id: "WLS01_GT2_PRESSURE"
  state_topic: "dt/gf/wls01/gt2/res"
  value_template: "{{ value_json['fields'].pressure_kPa }}"
  unit_of_measurement: "kPa"
  icon: "mdi:gauge"

# ───── Mixing Tank ─────
- name: "Water Level Sensor MX [Level]"
  unique_id: "WLS01_MX_LEVEL"
  state_topic: "dt/gf/wls01/mx/res"
  value_template: "{{ value_json['fields'].level_cm }}"
  unit_of_measurement: "cm"
  icon: "mdi:waves"

- name: "Water Level Sensor MX [Pressure]"
  unique_id: "WLS01_MX_PRESSURE"
  state_topic: "dt/gf/wls01/mx/res"
  value_template: "{{ value_json['fields'].pressure_kPa }}"
  unit_of_measurement: "kPa"
  icon: "mdi:gauge"

# ───── Freshwater Tank ─────
- name: "Water Level Sensor FWT [Level]"
  unique_id: "WLS01_FWT_LEVEL"
  state_topic: "dt/gf/wls01/fwt/res"
  value_template: "{{ value_json['fields'].level_cm }}"
  unit_of_measurement: "cm"
  icon: "mdi:waves"

- name: "Water Level Sensor FWT [Pressure]"
  unique_id: "WLS01_FWT_PRESSURE"
  state_topic: "dt/gf/wls01/fwt/res"
  value_template: "{{ value_json['fields'].pressure_kPa }}"
  unit_of_measurement: "kPa"
  icon: "mdi:gauge"



# ──────────────── HSI ────────────────

# === Scanner ===

- name: "HSI Scanner Status"
  state_topic: "status/gf/hs_scanner/state"
  value_template: "{{ value_json.status }}"
  unique_id: "hs_scanner_status"
  icon: mdi:scanner

# === CAMERA ===

- name: "HSI Camera Status"
  state_topic: "status/gf/hs_camera/camera_state"
  value_template: "{{ value_json.status }}"
  unique_id: "hs_camera_status"
  icon: mdi:camera

- name: "HSI Camera Exposure"
  state_topic: "status/gf/hs_camera/camera_state"
  value_template: "{{ value_json.EXPOSURE_TIME_MS }}"
  unit_of_measurement: "ms"
  unique_id: "hs_camera_exposure"
  icon: mdi:camera-timer

- name: "HSI Camera Gain"
  state_topic: "status/gf/hs_camera/camera_state"
  value_template: "{{ value_json.MASTER_GAIN }}"
  unique_id: "hs_camera_gain"
  icon: mdi:video-input-component

- name: "HSI Camera Black Level"
  state_topic: "status/gf/hs_camera/camera_state"
  value_template: "{{ value_json.BLACK_LEVEL }}"
  unique_id: "hs_camera_blacklevel"
  icon: mdi:contrast-box

# === PRINTER ===

- name: "HSI Printer Status"
  state_topic: "status/gf/hs_camera/printer_state"
  value_template: "{{ value_json.status }}"
  unique_id: "hs_printer_status"
  icon: mdi:printer-3d

- name: "HSI Printer X Step"
  state_topic: "status/gf/hs_camera/printer_state"
  value_template: "{{ value_json.X_STEP }}"
  unit_of_measurement: "mm"
  unique_id: "hs_printer_x_step"
  icon: mdi:arrow-expand-horizontal

- name: "HSI Printer X End"
  state_topic: "status/gf/hs_camera/printer_state"
  value_template: "{{ value_json.X_END }}"
  unit_of_measurement: "mm"
  unique_id: "hs_printer_x_end"
  icon: mdi:arrow-right-bold

- name: "HSI Printer Z Step"
  state_topic: "status/gf/hs_camera/printer_state"
  value_template: "{{ value_json.Z_STEP }}"
  unit_of_measurement: "mm"
  unique_id: "hs_printer_z_step"
  icon: mdi:arrow-expand-vertical

- name: "HSI Printer Z End"
  state_topic: "status/gf/hs_camera/printer_state"
  value_template: "{{ value_json.Z_END }}"
  unit_of_measurement: "mm"
  unique_id: "hs_printer_z_end"
  icon: mdi:arrow-down-bold
