# ┌────────────────────────────────────────────────────────────┐
# │                  Elixia Lamp Channel Controls              │
# │                     KYBFarm - Input Numbers                │
# └────────────────────────────────────────────────────────────┘

# ─────────────── Elixia Lamp 1 Raw Channel Levels ─────────────── #
elixia_1_channel_450nm:
  name: "[Elixia 1] Channel 450nm"
  icon: "mdi:waveform"
  initial: 0
  min: 0
  max: 1000
  step: 1
  mode: "box"

elixia_1_channel_660nm:
  name: "[Elixia 1] Channel 660nm"
  icon: "mdi:waveform"
  initial: 0
  min: 0
  max: 1000
  step: 1
  mode: "box"

elixia_1_channel_735nm:
  name: "[Elixia 1] Channel 735nm"
  icon: "mdi:waveform"
  initial: 0
  min: 0
  max: 1000
  step: 1
  mode: "box"

elixia_1_channel_5700k:
  name: "[Elixia 1] Channel 5700K"
  icon: "mdi:waveform"
  initial: 0
  min: 0
  max: 1000
  step: 1
  mode: "box"

# ─────────────── Elixia Lamp 2 Raw Channel Levels ─────────────── #
elixia_2_channel_450nm:
  name: "[Elixia 2] Channel 450nm"
  icon: "mdi:waveform"
  initial: 0
  min: 0
  max: 1000
  step: 1
  mode: "box"

elixia_2_channel_660nm:
  name: "[Elixia 2] Channel 660nm"
  icon: "mdi:waveform"
  initial: 0
  min: 0
  max: 1000
  step: 1
  mode: "box"

elixia_2_channel_735nm:
  name: "[Elixia 2] Channel 735nm"
  icon: "mdi:waveform"
  initial: 0
  min: 0
  max: 1000
  step: 1
  mode: "box"

elixia_2_channel_5700k:
  name: "[Elixia 2] Channel 5700K"
  icon: "mdi:waveform"
  initial: 0
  min: 0
  max: 1000
  step: 1
  mode: "box"

# ─────────────── Elixia Lamp 1 Set Channels ─────────────── #
elixia_1_set_channel_450nm:
  name: "[Elixia 1] Set Channel 450nm"
  icon: "mdi:waveform"
  initial: 0
  min: 0
  max: 1000
  step: 1
  mode: "box"

elixia_1_set_channel_5700k:
  name: "[Elixia 1] Set Channel 5700K"
  icon: "mdi:waveform"
  initial: 0
  min: 0
  max: 1000
  step: 1
  mode: "box"

elixia_1_set_channel_660nm:
  name: "[Elixia 1] Set Channel 660nm"
  icon: "mdi:waveform"
  initial: 0
  min: 0
  max: 1000
  step: 1
  mode: "box"

elixia_1_set_channel_735nm:
  name: "[Elixia 1] Set Channel 735nm"
  icon: "mdi:waveform"
  initial: 0
  min: 0
  max: 1000
  step: 1
  mode: "box"

# ─────────────── Elixia Lamp 2 Set Channels ─────────────── #
elixia_2_set_channel_450nm:
  name: "[Elixia 2] Set Channel 450nm"
  icon: "mdi:waveform"
  initial: 0
  min: 0
  max: 1000
  step: 1
  mode: "box"

elixia_2_set_channel_5700k:
  name: "[Elixia 2] Set Channel 5700K"
  icon: "mdi:waveform"
  initial: 0
  min: 0
  max: 1000
  step: 1
  mode: "box"

elixia_2_set_channel_660nm:
  name: "[Elixia 2] Set Channel 660nm"
  icon: "mdi:waveform"
  initial: 0
  min: 0
  max: 1000
  step: 1
  mode: "box"

elixia_2_set_channel_735nm:
  name: "[Elixia 2] Set Channel 735nm"
  icon: "mdi:waveform"
  initial: 0
  min: 0
  max: 1000
  step: 1
  mode: "box"

# ─────────────── Ref values ─────────────── #
ec_ref:
  name: "[Mixing Tank] EC Reference"
  icon: "mdi:water-opacity"
  initial: 0
  min: 0
  max: 2
  step: 0.05
  mode: "box"

intake_fan_temp_low:
  name: "[Intake Fan] Min Temperature"
  icon: "mdi:thermometer-minus"
  initial: 24
  min: 0
  max: 30
  step: 1
  mode: "box"

intake_fan_temp_high:
  name: "[Intake Fan] Max Temperature"
  icon: "mdi:thermometer-plus"
  initial: 25
  min: 0
  max: 30
  step: 1
  mode: "box"

intake_fan_humid_low:
  name: "[Intake Fan] Min Humidity"
  icon: "mdi:water-percent-alert"
  initial: 60
  min: 0
  max: 100
  step: 1
  mode: "box"

intake_fan_humid_high:
  name: "[Intake Fan] Max Humidity"
  icon: "mdi:water-percent"
  initial: 70
  min: 0
  max: 100
  step: 1
  mode: "box"

humid_ref:
  name: "[HVAC] Target Humidity"
  icon: "mdi:water-check"
  initial: 50
  min: 30
  max: 80
  step: 0.1
  mode: "box"

temp_ref:
  name: "[HVAC] Target Temperature"
  icon: "mdi:thermostat"
  initial: 20
  min: 10
  max: 50
  step: 0.1
  mode: "box"

co2_ref:
  name: "[HVAC] Target CO₂"
  icon: "mdi:molecule-co2"
  initial: 400
  min: 300
  max: 1000
  step: 10
  mode: "box"

ssr_duty_cycle:
  name: "[SSR] Duty Cycle"
  icon: "mdi:chart-donut"
  initial: 0
  min: 0
  max: 1
  step: 0.1
  mode: "box"

ssr_base_period:
  name: "[SSR] Base Period (s)"
  icon: "mdi:clock-outline"
  initial: 1
  min: 0.1
  max: 20
  step: 0.1
  mode: "box"

ssr_turn_on_for:
  name: "[SSR] On Time (s)"
  icon: "mdi:timer-play-outline"
  initial: 0
  min: 0
  max: 60
  step: 1
  mode: "box"

new_intake_fan_voltage:
  name: "[Fan] Manual Voltage (V)"
  icon: "mdi:fan-chevron-up"
  initial: 0
  min: 0
  max: 10
  step: 0.1
  mode: "box"

valve_voltage:
  name: "[Valve] Manual Voltage (V)"
  icon: "mdi:valve"
  initial: 0
  min: 0
  max: 10
  step: 0.1
  mode: "box"


# ─────────────── Elixia Lamp1 Dawn and Dusk durations ─────────────── #

elixia_1_dawn_duration_450nm:
  name: "[Elixia 1] Dawn Duration 450nm"
  icon: "mdi:white-balance-sunny"
  initial: 5
  min: 0
  max: 180
  step: 1
  unit_of_measurement: "min"
  mode: "box"

elixia_1_dusk_duration_450nm:
  name: "[Elixia 1] Dusk Duration 450nm"
  icon: "mdi:weather-night"
  initial: 5
  min: 0
  max: 180
  step: 1
  unit_of_measurement: "min"
  mode: "box"

elixia_1_dawn_duration_5700k:
  name: "[Elixia 1] Dawn Duration 5700K"
  icon: "mdi:white-balance-sunny"
  initial: 5
  min: 0
  max: 180
  step: 1
  unit_of_measurement: "min"
  mode: "box"

elixia_1_dusk_duration_5700k:
  name: "[Elixia 1] Dusk Duration 5700K"
  icon: "mdi:weather-night"
  initial: 5
  min: 0
  max: 180
  step: 1
  unit_of_measurement: "min"
  mode: "box"

elixia_1_dawn_duration_660nm:
  name: "[Elixia 1] Dawn Duration 660nm"
  icon: "mdi:white-balance-sunny"
  initial: 5
  min: 0
  max: 180
  step: 1
  unit_of_measurement: "min"
  mode: "box"

elixia_1_dusk_duration_660nm:
  name: "[Elixia 1] Dusk Duration 660nm"
  icon: "mdi:weather-night"
  initial: 5
  min: 0
  max: 180
  step: 1
  unit_of_measurement: "min"
  mode: "box"

elixia_1_dawn_duration_735nm:
  name: "[Elixia 1] Dawn Duration 735nm"
  icon: "mdi:white-balance-sunny"
  initial: 5
  min: 0
  max: 180
  step: 1
  unit_of_measurement: "min"
  mode: "box"

elixia_1_dusk_duration_735nm:
  name: "[Elixia 1] Dusk Duration 735nm"
  icon: "mdi:weather-night"
  initial: 5
  min: 0
  max: 180
  step: 1
  unit_of_measurement: "min"
  mode: "box"

# ─────────────── Elixia Lamp2 Dawn and Dusk durations ─────────────── #

elixia_2_dawn_duration_450nm:
  name: "[Elixia 2] Dawn Duration 450nm"
  icon: "mdi:white-balance-sunny"
  initial: 5
  min: 0
  max: 180
  step: 1
  unit_of_measurement: "min"
  mode: "box"

elixia_2_dusk_duration_450nm:
  name: "[Elixia 2] Dusk Duration 450nm"
  icon: "mdi:weather-night"
  initial: 5
  min: 0
  max: 180
  step: 1
  unit_of_measurement: "min"
  mode: "box"

elixia_2_dawn_duration_5700k:
  name: "[Elixia 2] Dawn Duration 5700K"
  icon: "mdi:white-balance-sunny"
  initial: 5
  min: 0
  max: 180
  step: 1
  unit_of_measurement: "min"
  mode: "box"

elixia_2_dusk_duration_5700k:
  name: "[Elixia 2] Dusk Duration 5700K"
  icon: "mdi:weather-night"
  initial: 5
  min: 0
  max: 180
  step: 1
  unit_of_measurement: "min"
  mode: "box"

elixia_2_dawn_duration_660nm:
  name: "[Elixia 2] Dawn Duration 660nm"
  icon: "mdi:white-balance-sunny"
  initial: 5
  min: 0
  max: 180
  step: 1
  unit_of_measurement: "min"
  mode: "box"

elixia_2_dusk_duration_660nm:
  name: "[Elixia 2] Dusk Duration 660nm"
  icon: "mdi:weather-night"
  initial: 5
  min: 0
  max: 180
  step: 1
  unit_of_measurement: "min"
  mode: "box"

elixia_2_dawn_duration_735nm:
  name: "[Elixia 2] Dawn Duration 735nm"
  icon: "mdi:white-balance-sunny"
  initial: 5
  min: 0
  max: 180
  step: 1
  unit_of_measurement: "min"
  mode: "box"

elixia_2_dusk_duration_735nm:
  name: "[Elixia 2] Dusk Duration 735nm"
  icon: "mdi:weather-night"
  initial: 5
  min: 0
  max: 180
  step: 1
  unit_of_measurement: "min"
  mode: "box"

# ─────────────── PIDs ─────────────── #
co2_pid_kp:
  name: "CO₂ PID – Kp"
  min: 0
  max: 1
  step: 0.01
  initial: 0.13
  mode: box
  icon: mdi:chart-line

co2_pid_ki:
  name: "CO₂ PID – Ki"
  min: 0
  max: 0.1
  step: 0.001
  initial: 0.02
  mode: box
  icon: mdi:sigma-lower

co2_pid_kd:
  name: "CO₂ PID – Kd"
  min: 0
  max: 0.1
  step: 0.001
  initial: 0.0
  mode: box
  icon: mdi:chart-bell-curve


cooling_pid_kp:
  name: "Cooling PID – Kp"
  min: 0
  max: 5
  step: 0.01
  mode: box
  icon: mdi:chart-line
  initial: 1.0

cooling_pid_ki:
  name: "Cooling PID – Ki"
  min: 0
  max: 1
  step: 0.001
  mode: box
  icon: mdi:sigma-lower
  initial: 0.05

cooling_pid_kd:
  name: "Cooling PID – Kd"
  min: 0
  max: 1
  step: 0.001
  mode: box
  icon: mdi:chart-bell-curve
  initial: 0.0


heating_pid_kp:
  name: "Heating PID – Kp"
  min: 0
  max: 10
  step: 0.01
  initial: 4.5
  mode: box
  icon: mdi:chart-line

heating_pid_ki:
  name: "Heating PID – Ki"
  min: 0
  max: 1
  step: 0.001
  initial: 0.25
  mode: box
  icon: mdi:sigma-lower

heating_pid_kd:
  name: "Heating PID – Kd"
  min: 0
  max: 1
  step: 0.001
  initial: 0.0
  mode: box
  icon: mdi:chart-bell-curve

# ─────────────── Nutrient ─────────────── #
nutrient_1_ref:
  name: "Nutrient 1 Reference"
  min: 0
  max: 10
  step: 0.1
  initial: 1.0
  mode: box
  icon: mdi:beaker

nutrient_2_ref:
  name: "Nutrient 2 Reference"
  min: 0
  max: 10
  step: 0.1
  initial: 1.0
  mode: box
  icon: mdi:beaker

nutrient_3_ref:
  name: "Nutrient 3 Reference"
  min: 0
  max: 10
  step: 0.1
  initial: 1.0
  mode: box
  icon: mdi:beaker


# ─────────────── HSI ─────────────── #

# === CAMERA ===

hs_camera_exposure:
  name: "HSI Camera – Exposure Time"
  min: 1
  max: 5000
  step: 1
  initial: 200
  mode: box
  unit_of_measurement: "ms"
  icon: mdi:camera-timer

hs_camera_gain:
  name: "HSI Camera – Master Gain"
  min: 0
  max: 100
  step: 1
  initial: 20
  mode: box
  icon: mdi:video-input-component

hs_camera_blacklevel:
  name: "HSI Camera – Black Level"
  min: 0
  max: 255
  step: 1
  initial: 10
  mode: box
  icon: mdi:contrast-box

# === PRINTER ===

hs_printer_x_step:
  name: "HSI Printer – X Step"
  min: 0.1
  max: 50
  step: 0.1
  initial: 5.0
  mode: box
  unit_of_measurement: "mm"
  icon: mdi:arrow-expand-horizontal

hs_printer_x_end:
  name: "HSI Printer – X End"
  min: 1
  max: 2000
  step: 1
  initial: 400
  mode: box
  unit_of_measurement: "mm"
  icon: mdi:arrow-right-bold

hs_printer_z_step:
  name: "HSI Printer – Z Step"
  min: 0.1
  max: 50
  step: 0.1
  initial: 5.0
  mode: box
  unit_of_measurement: "mm"
  icon: mdi:arrow-expand-vertical

hs_printer_z_end:
  name: "HSI Printer – Z End"
  min: 1
  max: 2000
  step: 1
  initial: 200
  mode: box
  unit_of_measurement: "mm"
  icon: mdi:arrow-down-bold