# ┌────────────────────────────────────────────────────────────┐
# │                  Input Text Entities - KYBFarm             │
# └────────────────────────────────────────────────────────────┘

calibration_status:
  name: "[Calibration] Status"
  icon: "mdi:chart-bell-curve"
  initial: "Normal Operation"
  mode: "text"

main_loop_flag:
    name: Main Loop Flag
    initial: "idle"
    max: 100