  lamp1_start_time:
    name: Lamp 1 start time 
    has_date: false
    has_time: true

  lamp1_finish_time:
    name: Lamp 1 end time 
    has_date: false
    has_time: true


  lamp2_start_time:
    name: Lamp 2 start time 
    has_date: false
    has_time: true

  lamp2_finish_time:
    name: Lamp 2 end time 
    has_date: false
    has_time: true