# ┌────────────────────────────────────────────────────────────────────────────┐
# │                        Home Assistant Input Booleans                       │
# │                     KYBFarm - Manual Control Switches                     │
# └────────────────────────────────────────────────────────────────────────────┘

relay_1:
  name: "[RL1] Water Pump 350"
  icon: "mdi:water-pump"

relay_2:
  name: "[RL2] Water Pump 5K"
  icon: "mdi:water-pump"

relay_3:
  name: "[RL3] Air Pump"
  icon: "mdi:chart-bubble"

relay_4:
  name: "[RL4] Internal Fans"
  icon: "mdi:fan"

relay_5:
  name: "[RL5] Intake Fan"
  icon: "mdi:fan-chevron-down"

relay_6:
  name: "[RL6] Humidifier"
  icon: "mdi:air-humidifier"

relay_7:
  name: "[RL7] Dehumidifier"
  icon: "mdi:air-humidifier-off"

relay_8:
  name: "[RL8] Heater"
  icon: "mdi:radiator"

relay_9:
  name: "[RL9] Extra"
  icon: "mdi:toggle-switch"

relay_10:
  name: "[RL10] Extra"
  icon: "mdi:toggle-switch"

relay_11:
  name: "[RL11] Solenoid 1"
  icon: "mdi:valve"

relay_12:
  name: "[RL12] Solenoid 2"
  icon: "mdi:valve"

relay_13:
  name: "[RL13] Co2 Solenoid"
  icon: "mdi:toggle-switch"

relay_14:
  name: "[RL14] Peristaltic Pump 1"
  icon: "mdi:pump"

relay_15:
  name: "[RL15] Peristaltic Pump 2"
  icon: "mdi:pump"

relay_16:
  name: "[RL16] Peristaltic Pump 3"
  icon: "mdi:pump"

solid_state_relay1:
  name: "[SSR1] Heating Battery"
  icon: "mdi:heating-coil"

solid_state_relay_stop_loop:
  name: "[SSR] Stop PWM Loop"
  icon: "mdi:power-off"

cooling_pid_enable_toggle:
  name: "[PID] Cooling Enable"
  icon: "mdi:thermometer-minus"

heating_pid_enable_toggle:
  name: "[PID] Heating Enable"
  icon: "mdi:thermometer-plus"

co2_pid_enable_toggle:
  name: "[PID] CO₂ Enable"
  icon: "mdi:molecule-co2"

tank_and_nutrient_control:
  name: "[CTRL] tank_and_nutrient_control"
  icon: "mdi:pot-mix"

intake_fan_toggle:
  name: "[CTRL] Intake Fan"
  icon: "mdi:fan"

fan_normal_operation_toggle:
  name: "[CTRL] Enable Normal Fan Op"
  icon: "mdi:fan-auto"

lamp1_control_toggle:
  name: "[CTRL] Lamp 1"
  icon: "mdi:ceiling-light"

lamp2_control_toggle:
  name: "[CTRL] Lamp 2"
  icon: "mdi:ceiling-light"
