# ┌────────────────────────────────────────────────────────────┐
# │                  Input Text Entities - KYBFarm             │
# └────────────────────────────────────────────────────────────┘

calibration_status:
  name: "[Calibration] Status"
  icon: "mdi:chart-bell-curve"
  initial: "Normal Operation"
  mode: "text"
