appdaemon:
  latitude: 0
  longitude: 0
  elevation: 30
  time_zone: Europe/Berlin
  log_level: "DEBUG"
  plugins:
    HASS:
      type: hass
      ha_url: http://172.26.31.3:8123
      cert_verify: True
      token: replace_this_with_long_lived_access_token_created_in_home_assistant
http:
  url: "http://0.0.0.0:5050"
admin:
api:
hadashboard:
