appdaemon:
  latitude: 0
  longitude: 0
  elevation: 30
  time_zone: Europe/Berlin
  log_level: "DEBUG"
  plugins:
    HASS:
      type: hass
      ha_url: http://172.26.64.197:8123
      cert_verify: True
      token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIyYzI5MDVhNDk0Nzg0NmY1YWQxNzkyMjU0ODg3Nzg4MiIsImlhdCI6MTc0OTIyMzAwOSwiZXhwIjoyMDY0NTgzMDA5fQ.b2mFONwe_HmX50CEKx3Hx43-FL66Kc4RUiZT4fTjlXA
http:
  url: "http://0.0.0.0:5050"
admin:
api:
hadashboard:
