# ┌────────────────────────────────────────────────────────────────────────────┐
# │                         Home Assistant Automation Config                   │
# │                      KYBFarm – PID Control Loop Triggers                  │
# └────────────────────────────────────────────────────────────────────────────┘

# ─────────────────────────────── [Cooling PID] Loop ───────────────────────────── #
- alias: "Cooling PID • Trigger"
  id: "cooling_pid_automation"
  trigger:
    - platform: state
      entity_id: input_text.main_loop_flag
      to: "cooling_pid"
  condition:
    - condition: state
      entity_id: input_boolean.cooling_pid_enable_toggle
      state: "on"
  action:
    - service: mqtt.publish
      data:
        topic: "cmd/cooling_pid/req"
        payload: '{"cmd": "pid_enable"}'
  mode: single

# ─────────────────────────────── [Heating PID] Loop ───────────────────────────── #
- alias: "Heating PID • Trigger"
  id: "heating_pid_automation"
  trigger:
    - platform: state
      entity_id: input_text.main_loop_flag
      to: "heating_pid"
  condition:
    - condition: state
      entity_id: input_boolean.heating_pid_enable_toggle
      state: "on"
  action:
    - service: mqtt.publish
      data:
        topic: "cmd/heating_pid/req"
        payload: '{"cmd": "pid_enable"}'
  mode: single

# ─────────────────────────────── [CO2 PID] Loop ──────────────────────────────── #
- alias: "CO2 PID • Trigger"
  id: "co2_pid_automation"
  trigger:
    - platform: state
      entity_id: input_text.main_loop_flag
      to: "co2_pid"
  condition:
    - condition: state
      entity_id: input_boolean.co2_pid_enable_toggle
      state: "on"
  action:
    - service: mqtt.publish
      data:
        topic: "cmd/co2_pid/req"
        payload: '{"cmd": "pid_enable"}'
  mode: single