# ┌────────────────────────────────────────────────────────────────────────────┐
# │                       Home Assistant Sensor Automations                    │
# │                   KYBFarm - MQTT Sensor Request Scheduler                  │
# └────────────────────────────────────────────────────────────────────────────┘

# ──────────────── S-PAR-02 GT1 ────────────────
- alias: "S-PAR-02 GT1 • Request"
  trigger:
    - platform: state
      entity_id: input_text.main_loop_flag
      to: "spar02_gt1"
  action:
    - service: mqtt.publish
      data:
        topic: "dt/gf/spar02/gt1/req"
        payload: '{"req_topic": "dt/gf/spar02/gt1/req", "res_topic": "dt/gf/spar02/gt1/res", "data": "ha_req"}'
  mode: single

# ──────────────── S-PAR-02 GT2 ────────────────
- alias: "S-PAR-02 GT2 • Request"
  trigger:
    - platform: state
      entity_id: input_text.main_loop_flag
      to: "spar02_gt2"
  action:
    - service: mqtt.publish
      data:
        topic: "dt/gf/spar02/gt2/req"
        payload: '{"req_topic": "dt/gf/spar02/gt2/req", "res_topic": "dt/gf/spar02/gt2/res", "data": "ha_req"}'
  mode: single

# ──────────────── S-EC-01 GT1 ────────────────
- alias: "S-EC-01 GT1 • Request"
  trigger:
    - platform: state
      entity_id: input_text.main_loop_flag
      to: "ec_gt1"
  action:
    - service: mqtt.publish
      data:
        topic: "dt/gf/sec01/gt1/req"
        payload: '{"req_topic": "dt/gf/sec01/gt1/req", "res_topic": "dt/gf/sec01/gt1/res", "data": "ha_req"}'
  mode: single

# ──────────────── S-EC-01 GT2 ────────────────
- alias: "S-EC-01 GT2 • Request"
  trigger:
    - platform: state
      entity_id: input_text.main_loop_flag
      to: "ec_gt2"
  action:
    - service: mqtt.publish
      data:
        topic: "dt/gf/sec01/gt2/req"
        payload: '{"req_topic": "dt/gf/sec01/gt2/req", "res_topic": "dt/gf/sec01/gt2/res", "data": "ha_req"}'
  mode: single

# ──────────────── S-EC-01 MX ────────────────
- alias: "S-EC-01 MX • Request"
  trigger:
    - platform: state
      entity_id: input_text.main_loop_flag
      to: "ec_mx"
  action:
    - service: mqtt.publish
      data:
        topic: "dt/gf/sec01/mx/req"
        payload: '{"req_topic": "dt/gf/sec01/mx/req", "res_topic": "dt/gf/sec01/mx/res", "data": "ha_req"}'
  mode: single

# ──────────────── S-PH-01 GT1 ────────────────
- alias: "S-PH-01 GT1 • Request"
  trigger:
    - platform: state
      entity_id: input_text.main_loop_flag
      to: "ph_gt1"
  action:
    - service: mqtt.publish
      data:
        topic: "dt/gf/sph01/gt1/req"
        payload: '{"req_topic": "dt/gf/sph01/gt1/req", "res_topic": "dt/gf/sph01/gt1/res", "data": "ha_req"}'
  mode: single

# ──────────────── S-PH-01 GT2 ────────────────
- alias: "S-PH-01 GT2 • Request"
  trigger:
    - platform: state
      entity_id: input_text.main_loop_flag
      to: "ph_gt2"
  action:
    - service: mqtt.publish
      data:
        topic: "dt/gf/sph01/gt2/req"
        payload: '{"req_topic": "dt/gf/sph01/gt2/req", "res_topic": "dt/gf/sph01/gt2/res", "data": "ha_req"}'
  mode: single

# ──────────────── S-PH-01 MX ────────────────
- alias: "S-PH-01 MX • Request"
  trigger:
    - platform: state
      entity_id: input_text.main_loop_flag
      to: "ph_mx"
  action:
    - service: mqtt.publish
      data:
        topic: "dt/gf/sph01/mx/req"
        payload: '{"req_topic": "dt/gf/sph01/mx/req", "res_topic": "dt/gf/sph01/mx/res", "data": "ha_req"}'
  mode: single

# ──────────────── STH01 1 ────────────────
- alias: "STH01 1 • Request"
  trigger:
    - platform: state
      entity_id: input_text.main_loop_flag
      to: "sth01_1"
  action:
    - service: mqtt.publish
      data:
        topic: "dt/gf/sth01/1/req"
        payload: '{"req_topic": "dt/gf/sth01/1/req", "res_topic": "dt/gf/sth01/1/res", "data": "ha_req"}'
  mode: single

# ──────────────── STH01 2 ────────────────
- alias: "STH01 2 • Request"
  trigger:
    - platform: state
      entity_id: input_text.main_loop_flag
      to: "sth01_2"
  action:
    - service: mqtt.publish
      data:
        topic: "dt/gf/sth01/2/req"
        payload: '{"req_topic": "dt/gf/sth01/2/req", "res_topic": "dt/gf/sth01/2/res", "data": "ha_req"}'
  mode: single

# ──────────────── S-YM-01 • Leaf Wetness ────────────────
- alias: "S-YM-01 • Request"
  trigger:
    - platform: state
      entity_id: input_text.main_loop_flag
      to: "sym01"
  action:
    - service: mqtt.publish
      data:
        topic: "dt/gf/sym01/req"
        payload: '{"req_topic": "dt/gf/sym01/req", "res_topic": "dt/gf/sym01/res", "data": "ha_req"}'
  mode: single

# ──────────────── CO2VOC ────────────────
- alias: "CO2VOC • Request"
  trigger:
    - platform: state
      entity_id: input_text.main_loop_flag
      to: "co2voc"
  action:
    - service: mqtt.publish
      data:
        topic: "dt/gf/co2voc/1/req"
        payload: '{"req_topic": "dt/gf/co2voc/1/req", "res_topic": "dt/gf/co2voc/1/res", "data": "ha_req"}'
  mode: single
