# ┌────────────────────────────────────────────────────────────────────────────┐
# │                       Home Assistant Sensor Calibrations                   │
# │                 KYBFarm - MQTT Calibration Automation Scripts              │
# └────────────────────────────────────────────────────────────────────────────┘

# ─────────────────────────────── TEMPLATE FORMAT ───────────────────────────── #
# - alias: "Descriptive Calibration Step"
#   trigger:
#     - platform: state
#       entity_id:
#         - input_select.calibrate_sensor_id
#       from: ...
#       to: ...
#   action:
#     - service: input_text.set_value
#       data:
#         value: "Status message"
#       target:
#         entity_id: input_text.calibration_status
#     - service: mqtt.publish
#       data:
#         topic: "cmd/topic"
#         payload: '{"cmd": "...", "res_topic": "..."}'
# ───────────────────────────────────────────────────────────────────────────── #


# ─────────────────────────── S-EC-01-1 [EC Sensor 1] ───────────────────────── #
# ── 1413us/cm ── #
- alias: "Initiate calibration for EC sensor 1 1413us/cm"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ec_01_1
      from: "*"
      to: "Initiate calibration for EC 1413us/cm"
  action:
    - service: input_text.set_value
      data:
        value: "Immerse probe in 1413us/cm, register calibration after a while."
      target:
        entity_id: input_text.calibration_status
  mode: single

- alias: "Register calibration for EC sensor 1 1413us/cm"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ec_01_1
      from: "*"
      to: "Register calibration for EC 1413us/cm"
  action:
    - service: input_text.set_value
      data:
        value: "Registered calibration for EC sensor 1 for 1413us/cm reference."
      target:
        entity_id: input_text.calibration_status
    - service: mqtt.publish
      data:
        topic: "cmd/sec01/1/req"
        payload: '{"cmd": "calibrate_ec_1413", "res_topic": "dt/gf/sec01/1/res"}'
  mode: single

# ── Return to Normal Operation ── #
- alias: "Return to normal operation EC sensor 1"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ec_01_1
      from: "*"
      to: "Normal Operation"
  action:
    - service: input_text.set_value
      data:
        value: "Sensor has returned to normal operation."
      target:
        entity_id: input_text.calibration_status
  mode: single

# ── 12880us/cm ── #
- alias: "Initiate calibration for EC sensor 1 12880us/cm"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ec_01_1
      from: "*"
      to: "Initiate calibration for EC 12880us/cm"
  action:
    - service: input_text.set_value
      data:
        value: "Immerse probe in 12880us/cm, register calibration after a while."
      target:
        entity_id: input_text.calibration_status
  mode: single

- alias: "Register calibration for EC sensor 1 12880us/cm"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ec_01_1
      from: "*"
      to: "Register calibration for EC 12880us/cm"
  action:
    - service: input_text.set_value
      data:
        value: "Registered calibration for EC sensor 1 for 12880us/cm reference."
      target:
        entity_id: input_text.calibration_status
    - service: mqtt.publish
      data:
        topic: "cmd/sec01/1/req"
        payload: '{"cmd": "calibrate_ec_12880", "res_topic": "dt/gf/sec01/1/res"}'
  mode: single
# ───────────────────────────────────────────────────────────────────────────── #


# ─────────────────────────── S-EC-01-2 [EC Sensor 2] ───────────────────────── #
# ── 1413us/cm ── #
- alias: "Initiate calibration for EC sensor 2 1413us/cm"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ec_01_2
      from: "*"
      to: "Initiate calibration for EC 1413us/cm"
  action:
    - service: input_text.set_value
      data:
        value: "Immerse probe in 1413us/cm, register calibration after a while."
      target:
        entity_id: input_text.calibration_status
  mode: single

- alias: "Register calibration for EC sensor 2 1413us/cm"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ec_01_2
      from: "*"
      to: "Register calibration for EC 1413us/cm"
  action:
    - service: input_text.set_value
      data:
        value: "Registered calibration for EC sensor 2 for 1413us/cm reference."
      target:
        entity_id: input_text.calibration_status
    - service: mqtt.publish
      data:
        topic: "cmd/sec01/2/req"
        payload: '{"cmd": "calibrate_ec_1413", "res_topic": "dt/gf/sec01/2/res"}'
  mode: single

# ── Return to normal operation ── #
- alias: "Return to normal operation EC sensor 2"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ec_01_2
      from: "*"
      to: "Normal Operation"
  action:
    - service: input_text.set_value
      data:
        value: "Sensor has returned to normal operation."
      target:
        entity_id: input_text.calibration_status
  mode: single


# ── 12880us/cm ── #
- alias: "Initiate calibration for EC sensor 2 12880us/cm"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ec_01_2
      from: "*"
      to: "Initiate calibration for EC 12880us/cm"
  action:
    - service: input_text.set_value
      data:
        value: "Immerse probe in 12880us/cm, register calibration after a while."
      target:
        entity_id: input_text.calibration_status
  mode: single

- alias: "Register calibration for EC sensor 2 12880us/cm"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ec_01_2
      from: "*"
      to: "Register calibration for EC 12880us/cm"
  action:
    - service: input_text.set_value
      data:
        value: "Registered calibration for EC sensor 2 for 12880us/cm reference."
      target:
        entity_id: input_text.calibration_status
    - service: mqtt.publish
      data:
        topic: "cmd/sec01/2/req"
        payload: '{"cmd": "calibrate_ec_12880", "res_topic": "dt/gf/sec01/2/res"}'
  mode: single
# ───────────────────────────────────────────────────────────────────────────── #


# ────────────────────────────── S-PH-01-1 [pH Sensor 1] ────────────────────── #

# ── 4.01pH ── #
- alias: "Initiate calibration for pH sensor 1 (4.01pH)"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ph_01_1
      from: null
      to: Initiate calibration for pH 4.01
  action:
    - service: input_text.set_value
      data:
        value: Immerse probe in pH 4.01, register calibration after a while.
      target:
        entity_id: input_text.calibration_status

- alias: "Register calibration for pH sensor 1 (4.01pH)"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ph_01_1
      from: null
      to: Register calibration for pH 4.01
  action:
    - service: input_text.set_value
      data:
        value: Registered calibration for pH sensor 1 for 4.01pH reference.
      target:
        entity_id: input_text.calibration_status
    - service: mqtt.publish
      data:
        qos: 0
        retain: false
        topic: "cmd/sph01/1/req"
        payload: '{ "cmd": "calibrate_ph_0401", "res_topic": "dt/gf/sph01/1/res"}'

# ── Return to Normal Operation ── #
- alias: "Return to normal operation pH sensor 1"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ph_01_1
      from: null
      to: Normal Operation
  action:
    - service: input_text.set_value
      data:
        value: Sensor has returned to normal operation.
      target:
        entity_id: input_text.calibration_status

# ── 7.00pH ── #
- alias: "Initiate calibration for pH sensor 1 (7.00pH)"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ph_01_1
      from: null
      to: Initiate calibration for pH 7.00
  action:
    - service: input_text.set_value
      data:
        value: Immerse probe in pH 7.00, register calibration after a while.
      target:
        entity_id: input_text.calibration_status

- alias: "Register calibration for pH sensor 1 (7.00pH)"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ph_01_1
      from: null
      to: Register calibration for pH 7.00
  action:
    - service: input_text.set_value
      data:
        value: Registered calibration for pH sensor 1 for 7.00pH reference.
      target:
        entity_id: input_text.calibration_status
    - service: mqtt.publish
      data:
        qos: 0
        retain: false
        topic: "cmd/sph01/1/req"
        payload: '{ "cmd": "calibrate_ph_0700", "res_topic": "dt/gf/sph01/1/res"}'

# ── 10.01pH ── #
- alias: "Initiate calibration for pH sensor 1 (10.01pH)"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ph_01_1
      from: null
      to: Initiate calibration for pH 10.01
  action:
    - service: input_text.set_value
      data:
        value: Immerse probe in pH 10.01, register calibration after a while.
      target:
        entity_id: input_text.calibration_status

- alias: "Register calibration for pH sensor 1 (10.01pH)"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ph_01_1
      from: null
      to: Register calibration for pH 10.01
  action:
    - service: input_text.set_value
      data:
        value: Registered calibration for pH sensor 1 for 10.01pH reference.
      target:
        entity_id: input_text.calibration_status
    - service: mqtt.publish
      data:
        qos: 0
        retain: false
        topic: "cmd/sph01/1/req"
        payload: '{ "cmd": "calibrate_ph_1001", "res_topic": "dt/gf/sph01/1/res"}'
# ───────────────────────────────────────────────────────────────────────────── #


# ────────────────────────────── S-PH-01-2 [pH Sensor 2] ────────────────────── #

# ── 4.01pH ── #
- alias: "Initiate calibration for pH sensor 2 (4.01pH)"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ph_01_2
      from: null
      to: Initiate calibration for pH 4.01
  action:
    - service: input_text.set_value
      data:
        value: Immerse probe in pH 4.01, register calibration after a while.
      target:
        entity_id: input_text.calibration_status

- alias: "Register calibration for pH sensor 2 (4.01pH)"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ph_01_2
      from: null
      to: Register calibration for pH 4.01
  action:
    - service: input_text.set_value
      data:
        value: Registered calibration for pH sensor 2 for 4.01pH reference.
      target:
        entity_id: input_text.calibration_status
    - service: mqtt.publish
      data:
        qos: 0
        retain: false
        topic: "cmd/sph01/2/req"
        payload: '{ "cmd": "calibrate_ph_0401", "res_topic": "dt/gf/sph01/2/res"}'

# ── Return to Normal Operation ── #
- alias: "Return to normal operation pH sensor 2"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ph_01_2
      from: null
      to: Normal Operation
  action:
    - service: input_text.set_value
      data:
        value: Sensor has returned to normal operation.
      target:
        entity_id: input_text.calibration_status

# ── 7.00pH ── #
- alias: "Initiate calibration for pH sensor 2 (7.00pH)"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ph_01_2
      from: null
      to: Initiate calibration for pH 7.00
  action:
    - service: input_text.set_value
      data:
        value: Immerse probe in pH 7.00, register calibration after a while.
      target:
        entity_id: input_text.calibration_status

- alias: "Register calibration for pH sensor 2 (7.00pH)"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ph_01_2
      from: null
      to: Register calibration for pH 7.00
  action:
    - service: input_text.set_value
      data:
        value: Registered calibration for pH sensor 2 for 7.00pH reference.
      target:
        entity_id: input_text.calibration_status
    - service: mqtt.publish
      data:
        qos: 0
        retain: false
        topic: "cmd/sph01/2/req"
        payload: '{ "cmd": "calibrate_ph_0700", "res_topic": "dt/gf/sph01/2/res"}'

# ── 10.01pH ── #
- alias: "Initiate calibration for pH sensor 2 (10.01pH)"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ph_01_2
      from: null
      to: Initiate calibration for pH 10.01
  action:
    - service: input_text.set_value
      data:
        value: Immerse probe in pH 10.01, register calibration after a while.
      target:
        entity_id: input_text.calibration_status

- alias: "Register calibration for pH sensor 2 (10.01pH)"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ph_01_2
      from: null
      to: Register calibration for pH 10.01
  action:
    - service: input_text.set_value
      data:
        value: Registered calibration for pH sensor 2 for 10.01pH reference.
      target:
        entity_id: input_text.calibration_status
    - service: mqtt.publish
      data:
        qos: 0
        retain: false
        topic: "cmd/sph01/2/req"
        payload: '{ "cmd": "calibrate_ph_1001", "res_topic": "dt/gf/sph01/2/res"}'

# ───────────────────────────────────────────────────────────────────────────── #