# ┌────────────────────────────────────────────────────────────────────────────┐
# │                     Sensor Calibration Automations - KYBFarm              │
# │             EC Sensor Calibration [S-EC-01-1, S-EC-01-2] via MQTT          │
# └────────────────────────────────────────────────────────────────────────────┘

# ──────────────── S-EC-01-1 [EC Sensor 1] ────────────────

# Initiate 1413us/cm
- alias: "S-EC-01-1 • Initiate EC 1413us/cm"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ec_01_1
      from: "*"
      to: "Initiate calibration for EC 1413us/cm"
  action:
    - service: input_text.set_value
      data:
        value: "Immerse probe in 1413 µS/cm solution, then register calibration."
      target:
        entity_id: input_text.calibration_status
  mode: single

# Register 1413us/cm
- alias: "S-EC-01-1 • Register EC 1413us/cm"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ec_01_1
      from: "*"
      to: "Register calibration for EC 1413us/cm"
  action:
    - service: input_text.set_value
      data:
        value: "Calibration registered for 1413 µS/cm."
      target:
        entity_id: input_text.calibration_status
    - service: mqtt.publish
      data:
        topic: "cmd/sec01/1/req"
        payload: '{"cmd": "calibrate_ec_1413", "res_topic": "dt/gf/sec01/1/res"}'
  mode: single

# Initiate 12880us/cm
- alias: "S-EC-01-1 • Initiate EC 12880us/cm"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ec_01_1
      from: "*"
      to: "Initiate calibration for EC 12880us/cm"
  action:
    - service: input_text.set_value
      data:
        value: "Immerse probe in 12880 µS/cm solution, then register calibration."
      target:
        entity_id: input_text.calibration_status
  mode: single

# Register 12880us/cm
- alias: "S-EC-01-1 • Register EC 12880us/cm"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ec_01_1
      from: "*"
      to: "Register calibration for EC 12880us/cm"
  action:
    - service: input_text.set_value
      data:
        value: "Calibration registered for 12880 µS/cm."
      target:
        entity_id: input_text.calibration_status
    - service: mqtt.publish
      data:
        topic: "cmd/sec01/1/req"
        payload: '{"cmd": "calibrate_ec_12880", "res_topic": "dt/gf/sec01/1/res"}'
  mode: single

# Return to Normal
- alias: "S-EC-01-1 • Return to Normal"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ec_01_1
      from: "*"
      to: "Normal Operation"
  action:
    - service: input_text.set_value
      data:
        value: "S-EC-01-1 back to normal operation."
      target:
        entity_id: input_text.calibration_status
  mode: single


# ──────────────── S-EC-01-2 [EC Sensor 2] ────────────────

# Initiate 1413us/cm
- alias: "S-EC-01-2 • Initiate EC 1413us/cm"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ec_01_2
      from: "*"
      to: "Initiate calibration for EC 1413us/cm"
  action:
    - service: input_text.set_value
      data:
        value: "Immerse probe in 1413 µS/cm solution, then register calibration."
      target:
        entity_id: input_text.calibration_status
  mode: single

# Register 1413us/cm
- alias: "S-EC-01-2 • Register EC 1413us/cm"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ec_01_2
      from: "*"
      to: "Register calibration for EC 1413us/cm"
  action:
    - service: input_text.set_value
      data:
        value: "Calibration registered for 1413 µS/cm."
      target:
        entity_id: input_text.calibration_status
    - service: mqtt.publish
      data:
        topic: "cmd/sec01/2/req"
        payload: '{"cmd": "calibrate_ec_1413", "res_topic": "dt/gf/sec01/2/res"}'
  mode: single

# Initiate 12880us/cm
- alias: "S-EC-01-2 • Initiate EC 12880us/cm"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ec_01_2
      from: "*"
      to: "Initiate calibration for EC 12880us/cm"
  action:
    - service: input_text.set_value
      data:
        value: "Immerse probe in 12880 µS/cm solution, then register calibration."
      target:
        entity_id: input_text.calibration_status
  mode: single

# Register 12880us/cm
- alias: "S-EC-01-2 • Register EC 12880us/cm"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ec_01_2
      from: "*"
      to: "Register calibration for EC 12880us/cm"
  action:
    - service: input_text.set_value
      data:
        value: "Calibration registered for 12880 µS/cm."
      target:
        entity_id: input_text.calibration_status
    - service: mqtt.publish
      data:
        topic: "cmd/sec01/2/req"
        payload: '{"cmd": "calibrate_ec_12880", "res_topic": "dt/gf/sec01/2/res"}'
  mode: single

# Return to Normal
- alias: "S-EC-01-2 • Return to Normal"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ec_01_2
      from: "*"
      to: "Normal Operation"
  action:
    - service: input_text.set_value
      data:
        value: "S-EC-01-2 back to normal operation."
      target:
        entity_id: input_text.calibration_status
  mode: single

# ──────────────── S-PH-01-1 [pH Sensor 1] ────────────────

# Initiate 4.01pH
- alias: "S-PH-01-1 • Initiate pH 4.01"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ph_01_1
      from: null
      to: "Initiate calibration for pH 4.01"
  action:
    - service: input_text.set_value
      data:
        value: "Immerse probe in pH 4.01, then register calibration."
      target:
        entity_id: input_text.calibration_status

# Register 4.01pH
- alias: "S-PH-01-1 • Register pH 4.01"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ph_01_1
      from: null
      to: "Register calibration for pH 4.01"
  action:
    - service: input_text.set_value
      data:
        value: "Calibration registered for pH 4.01."
      target:
        entity_id: input_text.calibration_status
    - service: mqtt.publish
      data:
        topic: "cmd/sph01/1/req"
        payload: '{ "cmd": "calibrate_ph_0401", "res_topic": "dt/gf/sph01/1/res"}'

# Initiate 7.00pH
- alias: "S-PH-01-1 • Initiate pH 7.00"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ph_01_1
      from: null
      to: "Initiate calibration for pH 7.00"
  action:
    - service: input_text.set_value
      data:
        value: "Immerse probe in pH 7.00, then register calibration."
      target:
        entity_id: input_text.calibration_status

# Register 7.00pH
- alias: "S-PH-01-1 • Register pH 7.00"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ph_01_1
      from: null
      to: "Register calibration for pH 7.00"
  action:
    - service: input_text.set_value
      data:
        value: "Calibration registered for pH 7.00."
      target:
        entity_id: input_text.calibration_status
    - service: mqtt.publish
      data:
        topic: "cmd/sph01/1/req"
        payload: '{ "cmd": "calibrate_ph_0700", "res_topic": "dt/gf/sph01/1/res"}'

# Initiate 10.01pH
- alias: "S-PH-01-1 • Initiate pH 10.01"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ph_01_1
      from: null
      to: "Initiate calibration for pH 10.01"
  action:
    - service: input_text.set_value
      data:
        value: "Immerse probe in pH 10.01, then register calibration."
      target:
        entity_id: input_text.calibration_status

# Register 10.01pH
- alias: "S-PH-01-1 • Register pH 10.01"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ph_01_1
      from: null
      to: "Register calibration for pH 10.01"
  action:
    - service: input_text.set_value
      data:
        value: "Calibration registered for pH 10.01."
      target:
        entity_id: input_text.calibration_status
    - service: mqtt.publish
      data:
        topic: "cmd/sph01/1/req"
        payload: '{ "cmd": "calibrate_ph_1001", "res_topic": "dt/gf/sph01/1/res"}'

# Return to Normal
- alias: "S-PH-01-1 • Return to Normal"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ph_01_1
      from: null
      to: "Normal Operation"
  action:
    - service: input_text.set_value
      data:
        value: "S-PH-01-1 back to normal operation."
      target:
        entity_id: input_text.calibration_status


# ──────────────── S-PH-01-2 [pH Sensor 2] ────────────────

# Initiate 4.01pH
- alias: "S-PH-01-2 • Initiate pH 4.01"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ph_01_2
      from: null
      to: "Initiate calibration for pH 4.01"
  action:
    - service: input_text.set_value
      data:
        value: "Immerse probe in pH 4.01, then register calibration."
      target:
        entity_id: input_text.calibration_status

# Register 4.01pH
- alias: "S-PH-01-2 • Register pH 4.01"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ph_01_2
      from: null
      to: "Register calibration for pH 4.01"
  action:
    - service: input_text.set_value
      data:
        value: "Calibration registered for pH 4.01."
      target:
        entity_id: input_text.calibration_status
    - service: mqtt.publish
      data:
        topic: "cmd/sph01/2/req"
        payload: '{ "cmd": "calibrate_ph_0401", "res_topic": "dt/gf/sph01/2/res"}'

# Initiate 7.00pH
- alias: "S-PH-01-2 • Initiate pH 7.00"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ph_01_2
      from: null
      to: "Initiate calibration for pH 7.00"
  action:
    - service: input_text.set_value
      data:
        value: "Immerse probe in pH 7.00, then register calibration."
      target:
        entity_id: input_text.calibration_status

# Register 7.00pH
- alias: "S-PH-01-2 • Register pH 7.00"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ph_01_2
      from: null
      to: "Register calibration for pH 7.00"
  action:
    - service: input_text.set_value
      data:
        value: "Calibration registered for pH 7.00."
      target:
        entity_id: input_text.calibration_status
    - service: mqtt.publish
      data:
        topic: "cmd/sph01/2/req"
        payload: '{ "cmd": "calibrate_ph_0700", "res_topic": "dt/gf/sph01/2/res"}'

# Initiate 10.01pH
- alias: "S-PH-01-2 • Initiate pH 10.01"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ph_01_2
      from: null
      to: "Initiate calibration for pH 10.01"
  action:
    - service: input_text.set_value
      data:
        value: "Immerse probe in pH 10.01, then register calibration."
      target:
        entity_id: input_text.calibration_status

# Register 10.01pH
- alias: "S-PH-01-2 • Register pH 10.01"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ph_01_2
      from: null
      to: "Register calibration for pH 10.01"
  action:
    - service: input_text.set_value
      data:
        value: "Calibration registered for pH 10.01."
      target:
        entity_id: input_text.calibration_status
    - service: mqtt.publish
      data:
        topic: "cmd/sph01/2/req"
        payload: '{ "cmd": "calibrate_ph_1001", "res_topic": "dt/gf/sph01/2/res"}'

# Return to Normal
- alias: "S-PH-01-2 • Return to Normal"
  trigger:
    - platform: state
      entity_id: input_select.calibrate_s_ph_01_2
      from: null
      to: "Normal Operation"
  action:
    - service: input_text.set_value
      data:
        value: "S-PH-01-2 back to normal operation."
      target:
        entity_id: input_text.calibration_status