# ┌────────────────────────────────────────────────────────────────────────────┐
# │                       Home Assistant Sensor Automations                    │
# │                   KYBFarm - MQTT Sensor Request Scheduler                  │
# └────────────────────────────────────────────────────────────────────────────┘

# ──────────────── S-PAR-02 GT1 ────────────────
- alias: "S-PAR-02 GT1 • Request"
  trigger:
    - platform: time_pattern
      seconds: 2
    - platform: time_pattern
      seconds: 32
  action:
    - service: mqtt.publish
      data:
        topic: "dt/gf/spar02/gt1/req"
        payload: '{"req_topic": "dt/gf/spar02/gt1/req", "res_topic": "dt/gf/spar02/gt1/res", "data": "ha_req"}'
  mode: single

# ──────────────── S-PAR-02 GT2 ────────────────
- alias: "S-PAR-02 GT2 • Request"
  trigger:
    - platform: time_pattern
      seconds: 12
    - platform: time_pattern
      seconds: 42
  action:
    - service: mqtt.publish
      data:
        topic: "dt/gf/spar02/gt2/req"
        payload: '{"req_topic": "dt/gf/spar02/gt2/req", "res_topic": "dt/gf/spar02/gt2/res", "data": "ha_req"}'
  mode: single

# ──────────────── S-EC-01 GT1 ────────────────
- alias: "S-EC-01 GT1 • Request"
  trigger:
    - platform: time_pattern
      seconds: 3
    - platform: time_pattern
      seconds: 33
  action:
    - service: mqtt.publish
      data:
        topic: "dt/gf/sec01/gt1/req"
        payload: '{"req_topic": "dt/gf/sec01/gt1/req", "res_topic": "dt/gf/sec01/gt1/res", "data": "ha_req"}'
  mode: single

# ──────────────── S-EC-01 GT2 ────────────────
- alias: "S-EC-01 GT2 • Request"
  trigger:
    - platform: time_pattern
      seconds: 4
    - platform: time_pattern
      seconds: 34
  action:
    - service: mqtt.publish
      data:
        topic: "dt/gf/sec01/gt2/req"
        payload: '{"req_topic": "dt/gf/sec01/gt2/req", "res_topic": "dt/gf/sec01/gt2/res", "data": "ha_req"}'
  mode: single

# ──────────────── S-EC-01 MX ────────────────
- alias: "S-EC-01 MX • Request"
  trigger:
    - platform: time_pattern
      seconds: 14
    - platform: time_pattern
      seconds: 44
  action:
    - service: mqtt.publish
      data:
        topic: "dt/gf/sec01/mx/req"
        payload: '{"req_topic": "dt/gf/sec01/mx/req", "res_topic": "dt/gf/sec01/mx/res", "data": "ha_req"}'
  mode: single

# ──────────────── STH01 1 ────────────────
- alias: "STH01 1 • Request"
  trigger:
    - platform: time_pattern
      seconds: 5
      # High frequency for environmental data
  action:
    - service: mqtt.publish
      data:
        topic: "dt/gf/sth01/1/req"
        payload: '{"req_topic": "dt/gf/sth01/1/req", "res_topic": "dt/gf/sth01/1/res", "data": "ha_req"}'
  mode: single

# ──────────────── STH01 2 ────────────────
- alias: "STH01 2 • Request"
  trigger:
    - platform: time_pattern
      seconds: 8
    - platform: time_pattern
      seconds: 38
  action:
    - service: mqtt.publish
      data:
        topic: "dt/gf/sth01/2/req"
        payload: '{"req_topic": "dt/gf/sth01/2/req", "res_topic": "dt/gf/sth01/2/res", "data": "ha_req"}'
  mode: single

# ──────────────── S-PH-01 GT1 ────────────────
- alias: "S-PH-01 GT1 • Request"
  trigger:
    - platform: time_pattern
      seconds: 6
    - platform: time_pattern
      seconds: 36
  action:
    - service: mqtt.publish
      data:
        topic: "dt/gf/sph01/gt1/req"
        payload: '{"req_topic": "dt/gf/sph01/gt1/req", "res_topic": "dt/gf/sph01/gt1/res", "data": "ha_req"}'
  mode: single

# ──────────────── S-PH-01 GT2 ────────────────
- alias: "S-PH-01 GT2 • Request"
  trigger:
    - platform: time_pattern
      seconds: 7
    - platform: time_pattern
      seconds: 37
  action:
    - service: mqtt.publish
      data:
        topic: "dt/gf/sph01/gt2/req"
        payload: '{"req_topic": "dt/gf/sph01/gt2/req", "res_topic": "dt/gf/sph01/gt2/res", "data": "ha_req"}'
  mode: single

# ──────────────── S-PH-01 MX ────────────────
- alias: "S-PH-01 MX • Request"
  trigger:
    - platform: time_pattern
      seconds: 13
    - platform: time_pattern
      seconds: 43
  action:
    - service: mqtt.publish
      data:
        topic: "dt/gf/sph01/mx/req"
        payload: '{"req_topic": "dt/gf/sph01/mx/req", "res_topic": "dt/gf/sph01/mx/res", "data": "ha_req"}'
  mode: single

# ──────────────── S-YM-01 [Leaf Wetness Sensor] ────────────────
- alias: "S-YM-01 • Request"
  trigger:
    - platform: time_pattern
      seconds: 9
    - platform: time_pattern
      seconds: 39
  action:
    - service: mqtt.publish
      data:
        topic: "dt/gf/sym01/req"
        payload: '{"req_topic": "dt/gf/sym01/req", "res_topic": "dt/gf/sym01/res", "data": "ha_req"}'
  mode: single

# ──────────────── CO2VOC [CO2 Sensor] ────────────────
- alias: "CO2VOC • Request"
  trigger:
    - platform: time_pattern
      seconds: "/10"
  action:
    - service: mqtt.publish
      data:
        topic: "dt/gf/co2voc/1/req"
        payload: '{"req_topic": "dt/gf/co2voc/1/req", "res_topic": "dt/gf/co2voc/1/res", "data": "ha_req"}'
  mode: single
