FROM python:3.10.6

WORKDIR /app

# Install only the essentials
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy script and templates
COPY generate_configs.py .
COPY config_templates/ ./templates/

# Make output dir in case volume is empty
RUN mkdir -p /app/output

# Default command
CMD ["python", "generate_configs.py"]
