FROM python:3.10.6

# Create a directory for the app
# RUN mkdir /app

# Set the working directory
WORKDIR /app

# Copy the requirements file
COPY requirements.txt .

# Install the requirements
RUN pip install -r requirements.txt

# Copy the rest of the files
COPY . .

# Set the command to run the script
ENTRYPOINT [ "python", "./config_generator.py"]

