# ┌────────────────────────────────────────────────────────────────────────────┐
# │                            AppDaemon Apps Config                          │
# │                           KYBFarm - apps.yaml                             │
# └────────────────────────────────────────────────────────────────────────────┘

dummy_control:
  module: dummy_control
  class: DummyControl
  gain: 0.5
  reference_value: 22.0
  sensor: sensor.s_ec_01_2_temperature
  control_signal_topic: "ha/desktop_gf/actuators/temperature"

sensor_request_loop:
  module: sensor_request_loop
  class: MainLoop
  flag_entity: input_text.main_loop_flag

air_pump_controller:
  module: air_pump_controller
  class: Air_pump_controller
  id: input_boolean.relay_3

hsi_config_update:
  module: HSI_config_update
  class: HSIConfigUpdate
  apply_button_id: input_button.hs_apply_config

  # CAMERA
  camera_exposure_id: input_number.hs_camera_exposure
  camera_gain_id: input_number.hs_camera_gain
  camera_blacklevel_id: input_number.hs_camera_blacklevel

  # PRINTER
  printer_x_step_id: input_number.hs_printer_x_step
  printer_x_end_id: input_number.hs_printer_x_end
  printer_z_step_id: input_number.hs_printer_z_step
  printer_z_end_id: input_number.hs_printer_z_end

hsi_scheduler:
  module: HSI_scheduler
  class: HSIScheduler
  scan_time_id: input_datetime.hs_scan_time


co2_pid:
  module: co2_pid
  class: CO2PID
  co2_pid_enable_id: input_boolean.co2_pid_enable_toggle
  co2_sensor_id: sensor.co2_voc_sensor_1_co2
  co2_ref_id: input_number.co2_ref
  co2_pid_kp_id: input_number.co2_pid_kp
  co2_pid_ki_id: input_number.co2_pid_ki
  co2_pid_kd_id: input_number.co2_pid_kd
  relay_13_id: input_boolean.relay_13

cooling_pid:
  module: cooling_pid
  class: CoolingPID
  enable_id: input_boolean.cooling_pid_enable_toggle
  humid_sensor_id: sensor.sth_sensor_1_humidity_2
  ref_id: input_number.humid_ref
  kp_id: input_number.cooling_pid_kp
  ki_id: input_number.cooling_pid_ki
  kd_id: input_number.cooling_pid_kd
  fan_cmd_topic: cmd/fan_voltage/req
  valve_cmd_topic: cmd/valve_voltage/req

heating_pid:
  module: heating_pid
  class: HeatingPID
  enable_id: input_boolean.heating_pid_enable_toggle
  sensor_id: sensor.sth_sensor_1_temperature
  ref_id: input_number.temp_ref
  kp_id: input_number.heating_pid_kp
  ki_id: input_number.heating_pid_ki
  kd_id: input_number.heating_pid_kd
  relay_id: input_boolean.solid_state_relay1
  pwm_duty_cycle_id: input_number.ssr_duty_cycle
  pwm_base_period_id: input_number.ssr_base_period
  pwm_stop_id: input_boolean.solid_state_relay_stop_loop
  turn_on_for_id: input_number.ssr_turn_on_for

lamp1_controller:
  module: lamp_control
  class: Lamp_control
  name: "Lamp 1 Controller"
  amplitude_ids:
    - input_number.elixia_1_channel_450nm
    - input_number.elixia_1_channel_5700k
    - input_number.elixia_1_channel_660nm
    - input_number.elixia_1_channel_735nm
  set_values_ids:
    - input_number.elixia_1_set_channel_450nm
    - input_number.elixia_1_set_channel_5700k
    - input_number.elixia_1_set_channel_660nm
    - input_number.elixia_1_set_channel_735nm
  dawn_durations_ids:
    - input_number.elixia_1_dawn_duration_450nm
    - input_number.elixia_1_dawn_duration_5700k
    - input_number.elixia_1_dawn_duration_660nm
    - input_number.elixia_1_dawn_duration_735nm
  dusk_durations_ids:
    - input_number.elixia_1_dusk_duration_450nm
    - input_number.elixia_1_dusk_duration_5700k
    - input_number.elixia_1_dusk_duration_660nm
    - input_number.elixia_1_dusk_duration_735nm
  start_time_id: input_datetime.lamp1_start_time
  finish_time_id: input_datetime.lamp1_finish_time
  toggle_id: input_boolean.lamp1_control_toggle

lamp2_controller:
  module: lamp_control
  class: Lamp_control
  name: "Lamp 2 Controller"
  amplitude_ids:
    - input_number.elixia_2_channel_450nm
    - input_number.elixia_2_channel_5700k
    - input_number.elixia_2_channel_660nm
    - input_number.elixia_2_channel_735nm
  set_values_ids:
    - input_number.elixia_2_set_channel_450nm
    - input_number.elixia_2_set_channel_5700k
    - input_number.elixia_2_set_channel_660nm
    - input_number.elixia_2_set_channel_735nm
  dawn_durations_ids:
    - input_number.elixia_2_dawn_duration_450nm
    - input_number.elixia_2_dawn_duration_5700k
    - input_number.elixia_2_dawn_duration_660nm
    - input_number.elixia_2_dawn_duration_735nm
  dusk_durations_ids:
    - input_number.elixia_2_dusk_duration_450nm
    - input_number.elixia_2_dusk_duration_5700k
    - input_number.elixia_2_dusk_duration_660nm
    - input_number.elixia_2_dusk_duration_735nm
  start_time_id: input_datetime.lamp2_start_time
  finish_time_id: input_datetime.lamp2_finish_time
  toggle_id: input_boolean.lamp2_control_toggle

