# ┌────────────────────────────────────────────────────────────────────────────┐
# │                            AppDaemon Apps Config                          │
# │                           KYBFarm - apps.yaml                             │
# └────────────────────────────────────────────────────────────────────────────┘

dummy_control:
  module: dummy_control
  class: DummyControl
  gain: 0.5
  reference_value: 22.0
  sensor: sensor.s_ec_01_2_temperature
  control_signal_topic: "ha/desktop_gf/actuators/temperature"

main_loop:
  module: main_loop
  class: MainLoop
  flag_entity: input_text.main_loop_flag

air_pump_controller:
  module: air_pump_controller
  class: Air_pump_controller
  id: input_boolean.relay_3

co2_pid:
  module: co2_pid
  class: CO2PID
  co2_pid_enable_id: input_boolean.co2_pid_enable_toggle
  co2_sensor_id: sensor.co2_voc_sensor_1_co2
  co2_ref_id: input_number.co2_ref
  co2_pid_kp_id: input_number.co2_pid_kp
  co2_pid_ki_id: input_number.co2_pid_ki
  co2_pid_kd_id: input_number.co2_pid_kd


intake_fan_controller:
  module: intake_fan_controller
  class: Intake_fan_controller
  humidity_sensor_id: sensor.scd_41_humidity
  temp_sensor_id: sensor.scd_41_temperature
  intake_fan_id: input_boolean.relay_5
  humid_low_id: input_number.intake_fan_humid_low
  humid_high_id: input_number.intake_fan_humid_high
  temp_low_id: input_number.intake_fan_temp_low
  temp_high_id: input_number.intake_fan_temp_high
  toggle_id: input_boolean.intake_fan_toggle

lamp1_controller:
  module: lamp_control
  class: Lamp_control
  name: "Lamp 1 Controller"
  amplitude_ids:
    - input_number.elixia_1_channel_450nm
    - input_number.elixia_1_channel_5700k
    - input_number.elixia_1_channel_660nm
    - input_number.elixia_1_channel_735nm
  set_values_ids:
    - input_number.elixia_1_set_channel_450nm
    - input_number.elixia_1_set_channel_5700k
    - input_number.elixia_1_set_channel_660nm
    - input_number.elixia_1_set_channel_735nm
  dawn_durations_ids:
    - input_number.elixia_1_dawn_duration_450nm
    - input_number.elixia_1_dawn_duration_5700k
    - input_number.elixia_1_dawn_duration_660nm
    - input_number.elixia_1_dawn_duration_735nm
  dusk_durations_ids:
    - input_number.elixia_1_dusk_duration_450nm
    - input_number.elixia_1_dusk_duration_5700k
    - input_number.elixia_1_dusk_duration_660nm
    - input_number.elixia_1_dusk_duration_735nm
  start_time_id: input_datetime.lamp1_start_time
  finish_time_id: input_datetime.lamp1_finish_time
  toggle_id: input_boolean.lamp1_control_toggle

lamp2_controller:
  module: lamp_control
  class: Lamp_control
  name: "Lamp 2 Controller"
  amplitude_ids:
    - input_number.elixia_2_channel_450nm
    - input_number.elixia_2_channel_5700k
    - input_number.elixia_2_channel_660nm
    - input_number.elixia_2_channel_735nm
  set_values_ids:
    - input_number.elixia_2_set_channel_450nm
    - input_number.elixia_2_set_channel_5700k
    - input_number.elixia_2_set_channel_660nm
    - input_number.elixia_2_set_channel_735nm
  dawn_durations_ids:
    - input_number.elixia_2_dawn_duration_450nm
    - input_number.elixia_2_dawn_duration_5700k
    - input_number.elixia_2_dawn_duration_660nm
    - input_number.elixia_2_dawn_duration_735nm
  dusk_durations_ids:
    - input_number.elixia_2_dusk_duration_450nm
    - input_number.elixia_2_dusk_duration_5700k
    - input_number.elixia_2_dusk_duration_660nm
    - input_number.elixia_2_dusk_duration_735nm
  start_time_id: input_datetime.lamp2_start_time
  finish_time_id: input_datetime.lamp2_finish_time
  toggle_id: input_boolean.lamp2_control_toggle

