# - id: '1706627554665'
- alias: HA GF data request
  description: ''
  trigger:
  - platform: time_pattern
    seconds: /29
  condition: []
  action:
  - service: mqtt.publish
    metadata: {}
    data:
      qos: 0
      retain: false
      topic: req/desktop_gf/sensors/SCD41
      payload: '{"req_topic": "req/desktop_gf/sensors/SCD41", "res_topic": "res/ha/desktop_gf/sensors/SCD41",
        "data": "ha_req" }'
  mode: single
