# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/card-mod.js

# External service configuration

homeassistant:
  media_dirs:
    hsi: /config/HSI/debug_pictures
  allowlist_external_dirs:
    - /config/HSI/scanner_data
    - /config/HSI/debug_pictures
camera:
  platform: local_file
  name: HSI Debug Snapshot
  file_path: /config/HSI/debug_pictures/latest_debug_picture.png

mqtt:
  sensor: !include include/mqtt_sensor_topics.yaml

automation: !include_dir_merge_list include/Automations

influxdb: !include include/influxdb.yaml

# GUI helpers split into directory
input_number: !include include/GUI_helpers/input_number.yaml
input_boolean: !include include/GUI_helpers/input_boolean.yaml
input_select: !include include/GUI_helpers/input_select.yaml
input_text: !include include/GUI_helpers/input_text.yaml
input_datetime: !include include/GUI_helpers/input_datetime.yaml
input_button: !include include/GUI_helpers/input_button.yaml
