
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  name: !env_var HOME_ASSISTANT_NAME
  latitude: !env_var HOME_ASSISTANT_LATITUDE
  longitude: !env_var HOME_ASSISTANT_LONGITUDE
  elevation: !env_var HOME_ASSISTANT_ELEVATION
  unit_system: !env_var HOME_ASSISTANT_UNIT_SYSTEM
  currency: !env_var HOME_ASSISTANT_CURRENCY
  country: !env_var HOME_ASSISTANT_COUNTRY
  time_zone: !env_var TZ

influxdb:
  api_version: 2
  ssl: false
  host: !env_var INFLUXDB_CONTAINER_HOSTNAME
  port: !env_var INFLUXDB_CONTAINER_PORT
  token: !env_var DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
  organization: !env_var DOCKER_INFLUXDB_INIT_ORG
  bucket: !env_var DOCKER_INFLUXDB_INIT_BUCKET
  tags:
    source: HASS
  tags_attributes:
    - friendly_name
    - device_class
  default_measurement: units
  exclude:
    entity_globs:
      - sensor.sun_*
  include:
    domains:
      - sensor

mqtt:
  sensor:
    - unique_id: !env_var TEMPERATURE_SENSOR_SIMULATOR_01_UNIQUE_ID
      device_class: !env_var TEMPERATURE_SENSOR_SIMULATOR_01_DEVICE_CLASS
      state_topic: !env_var TEMPERATURE_SENSOR_SIMULATOR_01_PUBLISH_STATE_TOPIC
      value_template: !env_var TEMPERATURE_SENSOR_SIMULATOR_01_VALUE_TEMPLATE
      unit_of_measurement: !env_var TEMPERATURE_SENSOR_SIMULATOR_01_UNIT_OF_MEASUREMENT
      suggested_display_precision: !env_var TEMPERATURE_SENSOR_SIMULATOR_01_SUGGESTED_DISPLAY_PRECISION  # The number of decimals which should be used in the sensor's state when it's displayed.
      device:
        identifiers: !env_var TEMPERATURE_SENSOR_SIMULATOR_01_DEVICE_IDENTIFIERS
        name: !env_var TEMPERATURE_SENSOR_SIMULATOR_01_DEVICE_NAME

  # climate:  # (Not yet implemented)
  #   - unique_id: "heat_pump_simulator_01"
  #     modes:
  #       - "off"
  #       - "heat"
  #     min_temp: 0
  #     max_temp: 100
  #     temperature_command_topic: "homeassistant/climate/heat_pump_simulator_01/set"
  #     temperature_state_topic: "homeassistant/climate/heat_pump_simulator_01/state"
  #     temperature_state_template: "{{ value_json.value }}"
  #     temperature_unit: "C"
  #     device:
  #       identifiers: "heatpumpsimulator01"
  #       name: "Heat Pump Simulator"