  api_version: 2
  ssl: false
  host: !secret host_ip
  port: 8086
  token: !secret influxdb_token # !env_var DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
  organization: kybfarm
  bucket: FarmData
  tags:
    source: HA
  tags_attributes:
    - friendly_name
  default_measurement: units
  exclude:
    entities:
      - zone.home
    domains:
      - persistent_notification
      - person
  include:
    domains:
      - sensor
      - binary_sensor